"""Preconfigured capability sets for interfaces."""

from .database import (
    EXISTING_MODEL_CAPABILITIES,
    ORM_PERSISTENCE_CAPABILITIES,
    ORM_WRITABLE_CAPABILITIES,
    READ_ONLY_CAPABILITIES,
)
from .calculation import CALCULATION_CORE_CAPABILITIES

__all__ = [
    "CALCULATION_CORE_CAPABILITIES",
    "EXISTING_MODEL_CAPABILITIES",
    "ORM_PERSISTENCE_CAPABILITIES",
    "ORM_WRITABLE_CAPABILITIES",
    "READ_ONLY_CAPABILITIES",
]
