/**
 * Message type identifiers
 */
export const MESSAGE_TYPES = {
  // Webview -> Extension
  GET_LOCAL_DATA: 'GET_LOCAL_DATA',
  SAVE_STATE: 'SAVE_STATE',
  UPDATE_ISSUE: 'UPDATE_ISSUE',
  CREATE_ISSUE: 'CREATE_ISSUE',
  OPEN_ISSUE_FILE: 'OPEN_ISSUE_FILE',
  FETCH_EXECUTION_PROFILES: 'FETCH_EXECUTION_PROFILES',
  OPEN_URL: 'OPEN_URL',
  // Extension -> Webview
  DATA_UPDATED: 'DATA_UPDATED',
  REFRESH: 'REFRESH',
  SHOW_CREATE_VIEW: 'SHOW_CREATE_VIEW',
  EXECUTION_PROFILES: 'EXECUTION_PROFILES',
}
