__version__ = "1.4.0"

from .benchmarking.benchmarking import benchmark_model, benchmark_models
from .metrics import mae, mse, rmse, mape, smape
from .models import (
    HybridForecastNet,
    AutoHybridForecaster,
    MELDForecaster,
    AutoMELD,
    KNNForecaster,
    AutoKNN,
    PALF,
    AutoPALF,
    NEOForecaster,
    AutoNEO,
    AutoThetaAR,
    PolymathForecaster,
    AutoPolymath,
    FourierForecaster,
    AutoFourier,
    NaiveForecaster,
    AutoNaive,
    HoltWintersForecaster,
    AutoHoltWinters,
    SSAForecaster,
    AutoSSA,
    LocalLinearForecaster,
    AutoLocalLinear,
    EnsembleForecaster,
    AutoEnsemble,
    RIFTForecaster,
    AutoRIFT,
)

__all__ = [
    "mae",
    "mse",
    "rmse",
    "mape",
    "smape",
    "HybridForecastNet",
    "AutoHybridForecaster",
    "MELDForecaster",
    "AutoMELD",
    "KNNForecaster",
    "AutoKNN",
    "PALF",
    "AutoPALF",
    "NEOForecaster",
    "AutoNEO",
    "AutoThetaAR",
    "PolymathForecaster",
    "AutoPolymath",
    "FourierForecaster",
    "AutoFourier",
    "NaiveForecaster",
    "AutoNaive",
    "HoltWintersForecaster",
    "AutoHoltWinters",
    "SSAForecaster",
    "AutoSSA",
    "LocalLinearForecaster",
    "AutoLocalLinear",
    "EnsembleForecaster",
    "AutoEnsemble",
    "RIFTForecaster",
    "AutoRIFT",
    "benchmark_model",
    "benchmark_models",
]
