"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from raindrop_query.errors import RaindropQueryError
from raindrop_query.models import conversations_getop as models_conversations_getop
from raindrop_query.types import BaseModel
from typing import Optional


class ConversationsGetNotFoundErrorData(BaseModel):
    error: models_conversations_getop.ConversationsGetError


@dataclass(unsafe_hash=True)
class ConversationsGetNotFoundError(RaindropQueryError):
    r"""Conversation not found"""

    data: ConversationsGetNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: ConversationsGetNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
