ISO_639_1: set[str] = {
    'ca', 'hy', 'to', 'sq', 'te', 'ty', 'ar', 'ku', 'km', 'rm', 'sa', 'na',
    'hr', 'ny', 'nn', 'ae', 'ht', 'ii', 'ia', 'nr', 'mr', 'gv', 'lt', 'ha',
    'fr', 'el', 'hu', 'lv', 'sw', 'ig', 'gn', 'ak', 'ng', 'sr', 'ur', 'da',
    'si', 'ps', 'se', 'kg', 'de', 'lo', 'mn', 'eo', 'ce', 'vi', 'nl', 'ug',
    'ky', 'st', 'mk', 'it', 'fo', 'fj', 'fy', 'os', 'jv', 'mh', 'gd', 'ie',
    'ja', 'am', 'za', 'ch', 'dz', 'es', 'pt', 'cv', 'oj', 'bh', 'kv', 'sd',
    'bg', 'ss', 'ba', 'hz', 'tg', 'wo', 'zu', 'ik', 'kl', 'tt', 'ta', 'cu',
    'ne', 'pi', 'rw', 'sm', 'ti', 'lu', 'bo', 'uz', 'ff', 'kn', 'lb', 'ho',
    'eu', 'or', 'th', 'sl', 'ro', 'ru', 'io', 'an', 'cs', 'en', 'su', 'tl',
    'mi', 'nv', 'bs', 'ab', 'sc', 'kr', 'vo', 'ln', 'ml', 'mg', 'fa', 'is',
    'rn', 'nb', 'oc', 'my', 'fi', 'cy', 'kk', 'om', 'wa', 'li', 'no', 'tw',
    'bn', 'ks', 'ms', 'iu', 'sn', 'kj', 'ee', 'qu', 'tr', 'ka', 'ts', 'dv',
    'yi', 'br', 'id', 'la', 'pl', 'gl', 'av', 'be', 'gu', 'hi', 'ay', 'so',
    'kw', 'uk', 'co', 'sv', 'af', 've', 'ga', 'bm', 'zh', 'ko', 'lg', 'xh',
    'he', 'bi', 'mt', 'pa', 'sk', 'tn', 'az', 'as', 'sg', 'tk', 'ki', 'aa',
    'cr', 'yo', 'nd', 'et'
}

ISO_3166: set[str] = {
    'GG', 'GI', 'JO', 'NO', 'BH', 'TT', 'BA', 'OM', 'UY', 'MR', 'GP', 'MU',
    'BR', 'NU', 'ML', 'TC', 'MZ', 'GY', 'KI', 'BJ', 'CA', 'AG', 'GN', 'IO',
    'ST', 'LV', 'NZ', 'LA', 'EH', 'DO', 'VE', 'TF', 'FM', 'AD', 'SI', 'GQ',
    'AQ', 'VG', 'CR', 'SK', 'NC', 'TZ', 'TK', 'ER', 'CV', 'IL', 'SO', 'AS',
    'RW', 'MX', 'SA', 'AM', 'VA', 'GF', 'HM', 'PT', 'LC', 'MS', 'VU', 'BS',
    'AW', 'SV', 'KZ', 'DJ', 'QA', 'AE', 'PH', 'BV', 'HU', 'LK', 'GU', 'BD',
    'AL', 'CK', 'RU', 'MK', 'AT', 'KY', 'TV', 'GH', 'KN', 'PK', 'MM', 'VI',
    'WF', 'AI', 'BF', 'KP', 'YT', 'ES', 'KM', 'FI', 'PY', 'RO', 'IE', 'AU',
    'AO', 'IM', 'BG', 'SC', 'BN', 'PF', 'HR', 'GA', 'EE', 'AR', 'SZ', 'DE',
    'ZM', 'CF', 'HK', 'BB', 'EC', 'SG', 'DZ', 'IR', 'SY', 'CD', 'LU', 'DM',
    'MH', 'US', 'BE', 'GL', 'CH', 'MF', 'PE', 'NE', 'CM', 'CX', 'GB', 'PR',
    'MW', 'SD', 'MC', 'LR', 'MY', 'MQ', 'MO', 'BT', 'NI', 'PG', 'MA', 'TN',
    'SE', 'NR', 'LY', 'FK', 'TL', 'JM', 'IT', 'CC', 'BY', 'GM', 'HT', 'TD',
    'PN', 'JP', 'WS', 'ZA', 'YE', 'FJ', 'CU', 'ZW', 'PW', 'SR', 'TG', 'FO',
    'UG', 'BI', 'ET', 'BL', 'UA', 'GT', 'VN', 'PM', 'LT', 'VC', 'GW', 'SJ',
    'SM', 'TW', 'TR', 'MG', 'ID', 'AX', 'RS', 'LB', 'CO', 'PA', 'TJ', 'AZ',
    'JE', 'UM', 'CZ', 'CG', 'UZ', 'SN', 'TH', 'CN', 'IS', 'NG', 'NF', 'KH',
    'DK', 'KW', 'ME', 'SL', 'NA', 'KE', 'PS', 'TM', 'HN', 'SH', 'TO', 'EG',
    'CY', 'GD', 'CI', 'GR', 'LS', 'NL', 'CL', 'AN', 'AF', 'MV', 'GS', 'NP',
    'MD', 'GE', 'MN', 'MP', 'IQ', 'KR', 'PL', 'BO', 'BZ', 'IN', 'BW', 'MT',
    'SB', 'FR', 'RE', 'BM', 'KG', 'LI'
}

ISO_4217: set[str] = {
    'CHC', 'AUD', 'ADP', 'BWP', 'LRD', 'SSP', 'TND', 'GWP', 'TMT', 'SRD', 'CNY',
    'BYB', 'CHW', 'SEK', 'XFU', 'BGN', 'UGW', 'RSD', 'KRW', 'BOB', 'TPE', 'YER',
    'ILR', 'ALK', 'LAJ', 'MUR', 'VUV', 'ANG', 'XRE', 'DZD', 'SRG', 'SIT', 'TTD',
    'XCD', 'BND', 'ZWG', 'GQE', 'GEL', 'AZN', 'BRB', 'RWF', 'USS', 'MVR', 'RUR',
    'LSL', 'HTG', 'HKD', 'LUF', 'BOP', 'PYG', 'IEP', 'XAU', 'XPF', 'SDP', 'CLP',
    'XBA', 'GEK', 'UAK', 'GNE', 'BHD', 'CYP', 'SZL', 'BBD', 'EGP', 'VES', 'SDD',
    'XBD', 'ZWL', 'VEB', 'BIF', 'GHS', 'LYD', 'CRC', 'COU', 'AOK', 'MOP', 'XTS',
    'GNS', 'MZE', 'PKR', 'UYW', 'YUD', 'MRO', 'PTE', 'CZK', 'BRR', 'NAD', 'VND',
    'KGS', 'UGX', 'KZT', 'XBB', 'ISJ', 'CVE', 'GYD', 'CSD', 'KMF', 'SOS', 'DOP',
    'VED', 'NGN', 'UZS', 'CSK', 'NZD', 'LAK', 'BYN', 'BSD', 'ARP', 'MDL', 'RUB',
    'KWD', 'BDT', 'JOD', 'AZM', 'MWK', 'BAD', 'ILS', 'ZAL', 'TZS', 'ESA', 'TRL',
    'GRD', 'ATS', 'IQD', 'ROL', 'ZWR', 'CUC', 'RON', 'HNL', 'AED', 'UYN', 'UYI',
    'BUK', 'JMD', 'KES', 'AON', 'BOV', 'BGK', 'SBD', 'BGL', 'GTQ', 'SVC', 'XFO',
    'ETB', 'AMD', 'ZRN', 'VNC', 'GNF', 'LVL', 'TJS', 'AFN', 'PLN', 'STN', 'MKD',
    'UYP', 'MVQ', 'CLF', 'SLL', 'ALL', 'GHC', 'DEM', 'MXN', 'AOA', 'XOF', 'USD',
    'EUR', 'SAR', 'TRY', 'XPD', 'CAD', 'IDR', 'CHE', 'UAH', 'GMD', 'ITL', 'MMK',
    'ZAR', 'STD', 'ZMK', 'QAR', 'XSU', 'DDM', 'TWD', 'XBC', 'MYR', 'ZWC', 'LSM',
    'SLE', 'KPW', 'TJR', 'ESB', 'GWE', 'YUN', 'WST', 'MZN', 'UYU', 'SCR', 'ZMW',
    'COP', 'XPT', 'CHF', 'HRD', 'ERN', 'BRE', 'ZWN', 'ROK', 'PES', 'SUR', 'PEN',
    'XXX', 'CUP', 'LTL', 'TMM', 'CSJ', 'PEH', 'SDG', 'DJF', 'NIC', 'LKR', 'AFA',
    'PEI', 'UGS', 'NOK', 'IRR', 'PLZ', 'ECV', 'NIO', 'THB', 'YUM', 'XDR', 'XAF',
    'MAD', 'VEF', 'BGJ', 'EEK', 'BEF', 'ZWD', 'MTP', 'ECS', 'BZD', 'MXV', 'ARY',
    'MLF', 'SGD', 'SKK', 'PGK', 'XEU', 'BRL', 'LUC', 'FKP', 'BRC', 'KYD', 'HUF',
    'ARS', 'XAG', 'MNT', 'BEC', 'SYP', 'XUA', 'BYR', 'OMR', 'MGA', 'FRF', 'XCG',
    'NLG', 'AOR', 'TOP', 'BEL', 'FIM', 'MZM', 'LVR', 'JPY', 'ARA', 'USN', 'LUL',
    'MGF', 'BMD', 'ILP', 'YDD', 'DKK', 'LTT', 'INR', 'RHD', 'BTN', 'NPR', 'AYM',
    'KHR', 'MTL', 'PAB', 'BAM', 'GIP', 'FJD', 'MRU', 'BRN', 'AWG', 'CDF', 'MXP',
    'LBP', 'ISK', 'PHP', 'ZRZ', 'HRK', 'GBP', 'GHP', 'ESP', 'SHP'
}
