"""Keyword enumeration for FlowQuery tokenization."""

from enum import Enum


class Keyword(Enum):
    """Enumeration of all keywords in FlowQuery."""
    
    RETURN = "RETURN"
    MATCH = "MATCH"
    WHERE = "WHERE"
    CREATE = "CREATE"
    VIRTUAL = "VIRTUAL"
    MERGE = "MERGE"
    DELETE = "DELETE"
    DETACH = "DETACH"
    SET = "SET"
    REMOVE = "REMOVE"
    FOREACH = "FOREACH"
    WITH = "WITH"
    CALL = "CALL"
    YIELD = "YIELD"
    LOAD = "LOAD"
    HEADERS = "HEADERS"
    POST = "POST"
    FROM = "FROM"
    CSV = "CSV"
    JSON = "JSON"
    TEXT = "TEXT"
    AS = "AS"
    UNWIND = "UNWIND"
    SUM = "SUM"
    COLLECT = "COLLECT"
    DISTINCT = "DISTINCT"
    ORDER = "ORDER"
    BY = "BY"
    ASC = "ASC"
    DESC = "DESC"
    SKIP = "SKIP"
    LIMIT = "LIMIT"
    EOF = "EOF"
    CASE = "CASE"
    WHEN = "WHEN"
    THEN = "THEN"
    ELSE = "ELSE"
    END = "END"
    NULL = "NULL"
    IN = "IN"
