#!/usr/bin/env python3
"""Configuration constants exposed through client module.

This module re-exports all configuration constants so other modules
can access them through the client mediator instead of directly
from the config module.

Uses deferred imports to avoid circular dependencies.
"""


# Deferred import to avoid circular dependencies
# Import is wrapped in a function to delay resolution until after module init
def _get_constants():
    """Import constants from config module to break circular dependencies."""
    from mcp_fuzzer.config.core.constants import (
        CONTENT_TYPE_HEADER,
        DEFAULT_FORCE_KILL_TIMEOUT,
        DEFAULT_GRACEFUL_SHUTDOWN_TIMEOUT,
        DEFAULT_HTTP_ACCEPT,
        DEFAULT_MAX_TOTAL_FUZZING_TIME,
        DEFAULT_MAX_TOOL_TIME,
        DEFAULT_PROTOCOL_RUNS_PER_TYPE,
        DEFAULT_PROTOCOL_VERSION,
        DEFAULT_TIMEOUT,
        DEFAULT_TOOL_RUNS,
        DEFAULT_TOOL_TIMEOUT,
        JSON_CONTENT_TYPE,
        MCP_PROTOCOL_VERSION_HEADER,
        MCP_SESSION_ID_HEADER,
        PROCESS_CLEANUP_TIMEOUT,
        PROCESS_FORCE_KILL_TIMEOUT,
        PROCESS_TERMINATION_TIMEOUT,
        PROCESS_WAIT_TIMEOUT,
        SAFETY_ENV_ALLOWLIST,
        SAFETY_HEADER_DENYLIST,
        SAFETY_LOCAL_HOSTS,
        SAFETY_NO_NETWORK_DEFAULT,
        SAFETY_PROXY_ENV_DENYLIST,
        SSE_CONTENT_TYPE,
        WATCHDOG_DEFAULT_CHECK_INTERVAL,
        WATCHDOG_EXTRA_BUFFER,
        WATCHDOG_MAX_HANG_ADDITIONAL,
    )

    return {
        "CONTENT_TYPE_HEADER": CONTENT_TYPE_HEADER,
        "DEFAULT_FORCE_KILL_TIMEOUT": DEFAULT_FORCE_KILL_TIMEOUT,
        "DEFAULT_GRACEFUL_SHUTDOWN_TIMEOUT": DEFAULT_GRACEFUL_SHUTDOWN_TIMEOUT,
        "DEFAULT_HTTP_ACCEPT": DEFAULT_HTTP_ACCEPT,
        "DEFAULT_MAX_TOTAL_FUZZING_TIME": DEFAULT_MAX_TOTAL_FUZZING_TIME,
        "DEFAULT_MAX_TOOL_TIME": DEFAULT_MAX_TOOL_TIME,
        "DEFAULT_PROTOCOL_RUNS_PER_TYPE": DEFAULT_PROTOCOL_RUNS_PER_TYPE,
        "DEFAULT_PROTOCOL_VERSION": DEFAULT_PROTOCOL_VERSION,
        "DEFAULT_TIMEOUT": DEFAULT_TIMEOUT,
        "DEFAULT_TOOL_RUNS": DEFAULT_TOOL_RUNS,
        "DEFAULT_TOOL_TIMEOUT": DEFAULT_TOOL_TIMEOUT,
        "JSON_CONTENT_TYPE": JSON_CONTENT_TYPE,
        "MCP_PROTOCOL_VERSION_HEADER": MCP_PROTOCOL_VERSION_HEADER,
        "MCP_SESSION_ID_HEADER": MCP_SESSION_ID_HEADER,
        "PROCESS_CLEANUP_TIMEOUT": PROCESS_CLEANUP_TIMEOUT,
        "PROCESS_FORCE_KILL_TIMEOUT": PROCESS_FORCE_KILL_TIMEOUT,
        "PROCESS_TERMINATION_TIMEOUT": PROCESS_TERMINATION_TIMEOUT,
        "PROCESS_WAIT_TIMEOUT": PROCESS_WAIT_TIMEOUT,
        "SAFETY_ENV_ALLOWLIST": SAFETY_ENV_ALLOWLIST,
        "SAFETY_HEADER_DENYLIST": SAFETY_HEADER_DENYLIST,
        "SAFETY_LOCAL_HOSTS": SAFETY_LOCAL_HOSTS,
        "SAFETY_NO_NETWORK_DEFAULT": SAFETY_NO_NETWORK_DEFAULT,
        "SAFETY_PROXY_ENV_DENYLIST": SAFETY_PROXY_ENV_DENYLIST,
        "SSE_CONTENT_TYPE": SSE_CONTENT_TYPE,
        "WATCHDOG_DEFAULT_CHECK_INTERVAL": WATCHDOG_DEFAULT_CHECK_INTERVAL,
        "WATCHDOG_EXTRA_BUFFER": WATCHDOG_EXTRA_BUFFER,
        "WATCHDOG_MAX_HANG_ADDITIONAL": WATCHDOG_MAX_HANG_ADDITIONAL,
    }


# Import constants after module initialization
_constants = _get_constants()

# Export all constants
CONTENT_TYPE_HEADER = _constants["CONTENT_TYPE_HEADER"]
DEFAULT_FORCE_KILL_TIMEOUT = _constants["DEFAULT_FORCE_KILL_TIMEOUT"]
DEFAULT_GRACEFUL_SHUTDOWN_TIMEOUT = _constants["DEFAULT_GRACEFUL_SHUTDOWN_TIMEOUT"]
DEFAULT_HTTP_ACCEPT = _constants["DEFAULT_HTTP_ACCEPT"]
DEFAULT_MAX_TOTAL_FUZZING_TIME = _constants["DEFAULT_MAX_TOTAL_FUZZING_TIME"]
DEFAULT_MAX_TOOL_TIME = _constants["DEFAULT_MAX_TOOL_TIME"]
DEFAULT_PROTOCOL_RUNS_PER_TYPE = _constants["DEFAULT_PROTOCOL_RUNS_PER_TYPE"]
DEFAULT_PROTOCOL_VERSION = _constants["DEFAULT_PROTOCOL_VERSION"]
DEFAULT_TIMEOUT = _constants["DEFAULT_TIMEOUT"]
DEFAULT_TOOL_RUNS = _constants["DEFAULT_TOOL_RUNS"]
DEFAULT_TOOL_TIMEOUT = _constants["DEFAULT_TOOL_TIMEOUT"]
JSON_CONTENT_TYPE = _constants["JSON_CONTENT_TYPE"]
MCP_PROTOCOL_VERSION_HEADER = _constants["MCP_PROTOCOL_VERSION_HEADER"]
MCP_SESSION_ID_HEADER = _constants["MCP_SESSION_ID_HEADER"]
PROCESS_CLEANUP_TIMEOUT = _constants["PROCESS_CLEANUP_TIMEOUT"]
PROCESS_FORCE_KILL_TIMEOUT = _constants["PROCESS_FORCE_KILL_TIMEOUT"]
PROCESS_TERMINATION_TIMEOUT = _constants["PROCESS_TERMINATION_TIMEOUT"]
PROCESS_WAIT_TIMEOUT = _constants["PROCESS_WAIT_TIMEOUT"]
SAFETY_ENV_ALLOWLIST = _constants["SAFETY_ENV_ALLOWLIST"]
SAFETY_HEADER_DENYLIST = _constants["SAFETY_HEADER_DENYLIST"]
SAFETY_LOCAL_HOSTS = _constants["SAFETY_LOCAL_HOSTS"]
SAFETY_NO_NETWORK_DEFAULT = _constants["SAFETY_NO_NETWORK_DEFAULT"]
SAFETY_PROXY_ENV_DENYLIST = _constants["SAFETY_PROXY_ENV_DENYLIST"]
SSE_CONTENT_TYPE = _constants["SSE_CONTENT_TYPE"]
WATCHDOG_DEFAULT_CHECK_INTERVAL = _constants["WATCHDOG_DEFAULT_CHECK_INTERVAL"]
WATCHDOG_EXTRA_BUFFER = _constants["WATCHDOG_EXTRA_BUFFER"]
WATCHDOG_MAX_HANG_ADDITIONAL = _constants["WATCHDOG_MAX_HANG_ADDITIONAL"]

__all__ = [
    "DEFAULT_PROTOCOL_VERSION",
    "CONTENT_TYPE_HEADER",
    "JSON_CONTENT_TYPE",
    "SSE_CONTENT_TYPE",
    "DEFAULT_HTTP_ACCEPT",
    "MCP_SESSION_ID_HEADER",
    "MCP_PROTOCOL_VERSION_HEADER",
    "WATCHDOG_DEFAULT_CHECK_INTERVAL",
    "WATCHDOG_EXTRA_BUFFER",
    "WATCHDOG_MAX_HANG_ADDITIONAL",
    "SAFETY_LOCAL_HOSTS",
    "SAFETY_NO_NETWORK_DEFAULT",
    "SAFETY_HEADER_DENYLIST",
    "SAFETY_PROXY_ENV_DENYLIST",
    "SAFETY_ENV_ALLOWLIST",
    "DEFAULT_TOOL_RUNS",
    "DEFAULT_PROTOCOL_RUNS_PER_TYPE",
    "DEFAULT_TIMEOUT",
    "DEFAULT_TOOL_TIMEOUT",
    "DEFAULT_MAX_TOOL_TIME",
    "DEFAULT_MAX_TOTAL_FUZZING_TIME",
    "DEFAULT_GRACEFUL_SHUTDOWN_TIMEOUT",
    "DEFAULT_FORCE_KILL_TIMEOUT",
    "PROCESS_TERMINATION_TIMEOUT",
    "PROCESS_FORCE_KILL_TIMEOUT",
    "PROCESS_CLEANUP_TIMEOUT",
    "PROCESS_WAIT_TIMEOUT",
]
