# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/server/v1/release_notes.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chalk._gen.chalk.auth.v1 import permissions_pb2 as chalk_dot_auth_dot_v1_dot_permissions__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#chalk/server/v1/release_notes.proto\x12\x0f\x63halk.server.v1\x1a\x1f\x63halk/auth/v1/permissions.proto\x1a\x1fgoogle/protobuf/timestamp.proto"|\n\x07Release\x12\x18\n\x07version\x18\x01 \x01(\tR\x07version\x12\x18\n\x07\x63ontent\x18\x02 \x01(\tR\x07\x63ontent\x12=\n\x0cpublished_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bpublishedAt"3\n\x13ListReleasesRequest\x12\x1c\n\tcomponent\x18\x01 \x01(\tR\tcomponent"L\n\x14ListReleasesResponse\x12\x34\n\x08releases\x18\x01 \x03(\x0b\x32\x18.chalk.server.v1.ReleaseR\x08releases2z\n\x13ReleaseNotesService\x12\x63\n\x0cListReleases\x12$.chalk.server.v1.ListReleasesRequest\x1a%.chalk.server.v1.ListReleasesResponse"\x06\x90\x02\x01\x80}\x01\x42\x9a\x01\n\x13\x63om.chalk.server.v1B\x11ReleaseNotesProtoP\x01Z\x12server/v1;serverv1\xa2\x02\x03\x43SX\xaa\x02\x0f\x43halk.Server.V1\xca\x02\x0f\x43halk\\Server\\V1\xe2\x02\x1b\x43halk\\Server\\V1\\GPBMetadata\xea\x02\x11\x43halk::Server::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "chalk.server.v1.release_notes_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\023com.chalk.server.v1B\021ReleaseNotesProtoP\001Z\022server/v1;serverv1\242\002\003CSX\252\002\017Chalk.Server.V1\312\002\017Chalk\\Server\\V1\342\002\033Chalk\\Server\\V1\\GPBMetadata\352\002\021Chalk::Server::V1"
    _globals["_RELEASENOTESSERVICE"].methods_by_name["ListReleases"]._options = None
    _globals["_RELEASENOTESSERVICE"].methods_by_name["ListReleases"]._serialized_options = b"\220\002\001\200}\001"
    _globals["_RELEASE"]._serialized_start = 122
    _globals["_RELEASE"]._serialized_end = 246
    _globals["_LISTRELEASESREQUEST"]._serialized_start = 248
    _globals["_LISTRELEASESREQUEST"]._serialized_end = 299
    _globals["_LISTRELEASESRESPONSE"]._serialized_start = 301
    _globals["_LISTRELEASESRESPONSE"]._serialized_end = 377
    _globals["_RELEASENOTESSERVICE"]._serialized_start = 379
    _globals["_RELEASENOTESSERVICE"]._serialized_end = 501
# @@protoc_insertion_point(module_scope)
