"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SslTypeSystemSettingsConfAPITypedDict(TypedDict):
    cert_path: str
    disabled: bool
    passphrase: str
    priv_key_path: str
    ca_path: NotRequired[str]


class SslTypeSystemSettingsConfAPI(BaseModel):
    cert_path: Annotated[str, pydantic.Field(alias="certPath")]

    disabled: bool

    passphrase: str

    priv_key_path: Annotated[str, pydantic.Field(alias="privKeyPath")]

    ca_path: Annotated[Optional[str], pydantic.Field(alias="caPath")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["caPath"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
