"""
JavaScript Math builtin module.

Usage:

```python
import pulse.js.math as Math
Math.PI           # -> Math.PI
Math.floor(3.7)   # -> Math.floor(3.7)

from pulse.js.math import PI, floor
PI                # -> Math.PI
floor(3.7)        # -> Math.floor(3.7)
```
"""

from pulse.transpiler.js_module import JsModule

# Constants (type stubs for IDE support)
PI: float
E: float
LN2: float
LN10: float
LOG2E: float
LOG10E: float
SQRT1_2: float
SQRT2: float


# Methods (type stubs for IDE support)
def abs(x: float) -> float: ...
def acos(x: float) -> float: ...
def acosh(x: float) -> float: ...
def asin(x: float) -> float: ...
def asinh(x: float) -> float: ...
def atan(x: float) -> float: ...
def atan2(y: float, x: float) -> float: ...
def atanh(x: float) -> float: ...
def cbrt(x: float) -> float: ...
def ceil(x: float) -> int: ...
def clz32(x: int) -> int: ...
def cos(x: float) -> float: ...
def cosh(x: float) -> float: ...
def exp(x: float) -> float: ...
def expm1(x: float) -> float: ...
def floor(x: float) -> int: ...
def fround(x: float) -> float: ...
def hypot(*values: float) -> float: ...
def imul(x: int, y: int) -> int: ...
def log(x: float) -> float: ...
def log10(x: float) -> float: ...
def log1p(x: float) -> float: ...
def log2(x: float) -> float: ...
def max(*values: float) -> float: ...
def min(*values: float) -> float: ...
def pow(x: float, y: float) -> float: ...
def random() -> float: ...
def round(x: float) -> int: ...
def sign(x: float) -> int: ...
def sin(x: float) -> float: ...
def sinh(x: float) -> float: ...
def sqrt(x: float) -> float: ...
def tan(x: float) -> float: ...
def tanh(x: float) -> float: ...
def trunc(x: float) -> int: ...


# Self-register this module as a JS builtin
JsModule.register(name="Math")
