"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import utils
from enum import Enum


class PaginationOptionsRestDiscoveryDiscoverTypeHTTPPagination(
    str, Enum, metaclass=utils.OpenEnumMeta
):
    # None
    NONE = "none"
    # Response Body Attribute
    RESPONSE_BODY = "response_body"
    # Response Header Attribute
    RESPONSE_HEADER = "response_header"
    # RFC 5988 - Web Linking
    RESPONSE_HEADER_LINK = "response_header_link"
    # Offset/Limit
    REQUEST_OFFSET = "request_offset"
    # Page/Size
    REQUEST_PAGE = "request_page"
