# coding: utf-8

"""
    Swifty OAuth API

    API for the Swifty OAuth Backend 

    The version of the OpenAPI document: 1.0.0
    Contact: paul.tindall@rxfoundry.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rxfoundry.clients.swifty_oauth_api.models.oauth_token_post_request import OauthTokenPostRequest

class TestOauthTokenPostRequest(unittest.TestCase):
    """OauthTokenPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OauthTokenPostRequest:
        """Test OauthTokenPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OauthTokenPostRequest`
        """
        model = OauthTokenPostRequest()
        if include_optional:
            return OauthTokenPostRequest(
                grant_type = '',
                username = '',
                password = '',
                refresh_token = ''
            )
        else:
            return OauthTokenPostRequest(
        )
        """

    def testOauthTokenPostRequest(self):
        """Test OauthTokenPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
