EXPENSIVE_WORDS = {
    "i am": "i'm",
    "do not": "don't",
    "would not": "wouldn't",
    "i will": "i'll",
    "thank you": "thanks",
    "large language model": "llm",
    "i have": "i've",
    "you are": "you're",
    "we will": "we'll",
    "they are": "they're",
    "it is": "it's",
    "could have": "could've",
    "should not": "shouldn't",
    "has not": "hasn't",
    "there is": "there's",
    "as soon as possible": "asap",
    "frequently asked questions": "faq",
    "user interface": "ui",
    "to be determined": "tbd",
    "by the way": "btw",
    "artificial intelligence": "ai",
    "point of view": "pov",
    "for your information": "fyi",
    "going to": "gonna",
    "want to": "wanna",
    "got to": "gotta",
    "give me": "gimme",
    "kind of": "kinda",
    "don't know": "dunno",
    "doctor": "dr.",
    "street": "st.",
    "avenue": "ave.",
    "incorporated": "inc.",
    "estimated time of arrival": "eta",
    "end of day": "eod",
    "utility": "util",
    "laboratory": "lab",
    "photograph": "photo",
    "refrigerator": "fridge",
    "vegetables": "veggies",
    "mathematics": "math",
    "gymnasium": "gym",
    "advertisement": "ad",
    "herbivorious": "veg",
    "vegetarian": "veg",
    "carnivorious": "non veg",
    "non-vegetarian": "non-veg",
    "non vegetarian": "non veg",
    "ecstatic": "very happy",
    "elated": "very happy",
    "overjoyed": "very happy",
    "jubilant": "very happy",
    "blissful": "very happy",
    "euphoric": "very happy",
    "delighted": "very happy",
    "thrilled": "very happy",
    "cheerful": "very happy",
    "glad": "very happy",
    "on cloud nine": "very happy",
    "walking on air": "very happy",
    "approximate": "approx",
    "regarding": "re:",
    "information": "info",
    "amount": "amt",
    "reference": "ref",
    "management": "mgmt",
    "number": "no.",
    "because": "as",
    "without": "w/o",
    "before": "b4",
    "between": "btw",
    "example": "e.g.",
    "demonstrate": "show",
    "utilize": "use",
    "purchase": "buy",
    "sufficient": "enough",
    "assist": "help",
    "request": "ask",
    "inexpensive": "cheap",
    "tomorrow": "tmrw",
    "message": "msg",
    "people": "ppl",
    "please": "pls",
    "thank you": "thanks",
    "business": "biz",
    "favorite": "fav",
    "every": "ea.",
    "minute": "min",
    "second": "sec",
    "annually": "yearly",
    "and": "&",
    "resulting in": "leads to",
    "check": "verify",
    "important": "imp.",
    "versus": "vs",
    "determine": "find",
    "terminate": "end",
    "initialize": "start",
    "facilitate": "ease or run",
    "commence": "begin",
    "equivalent": "same",
    "acquire": "get",
    "maximum": "max",
    "minimum": "min",
    "miscellaneous": "misc",
    "introduction": "intro",
    "definition": "def",
    "character": "char",
    "equation": "eq",
    "weight": "wt",
    "height": "ht",
    "quantity": "qty",
    "average": "avg",
    "standard": "std",
    "package": "pkg",
    "document": "doc",
    "government": "govt",
    "january": "jan",
    "february": "feb",
    "august": "aug",
    "september": "sept",
    "october": "oct",
    "november": "nov",
    "december": "dec",
    "monday": "mon",
    "tuesday": "tue",
    "wednesday": "wed",
    "thursday": "thur",
    "friday": "fri",
    "saturday": "sat",
    "sunday": "sun",
}