"""
Centralized constants for the RXON protocol.
Shared between Orchestrator and Worker SDK.
"""

__all__ = [
    "AUTH_HEADER_CLIENT",
    "AUTH_HEADER_WORKER",
    "ERROR_CODE_TRANSIENT",
    "ERROR_CODE_PERMANENT",
    "ERROR_CODE_INVALID_INPUT",
    "ERROR_CODE_INTEGRITY_MISMATCH",
    "ERROR_CODE_TIMEOUT",
    "ERROR_CODE_RESOURCE_EXHAUSTED",
    "ERROR_CODE_DEPENDENCY",
    "ERROR_CODE_SECURITY",
    "ERROR_CODE_INTERNAL",
    "TASK_STATUS_SUCCESS",
    "TASK_STATUS_FAILURE",
    "TASK_STATUS_CANCELLED",
    "COMMAND_CANCEL_TASK",
    "MSG_TYPE_PROGRESS",
    "STS_TOKEN_ENDPOINT",
    "WS_ENDPOINT",
    "ENDPOINT_WORKER_REGISTER",
    "ENDPOINT_TASK_NEXT",
    "ENDPOINT_TASK_RESULT",
    "ENDPOINT_WORKER_HEARTBEAT",
    "JOB_STATUS_PENDING",
    "JOB_STATUS_WAITING_FOR_WORKER",
    "JOB_STATUS_RUNNING",
    "JOB_STATUS_FINISHED",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_ERROR",
    "JOB_STATUS_QUARANTINED",
    "JOB_STATUS_CANCELLED",
    "JOB_STATUS_WAITING_FOR_HUMAN",
    "JOB_STATUS_WAITING_FOR_PARALLEL",
    "WORKER_API_PREFIX",
    "PROTOCOL_VERSION",
]

# --- Protocol Metadata ---
PROTOCOL_VERSION = "1.0"

# --- Auth Headers ---
AUTH_HEADER_CLIENT = "X-Client-Token"
AUTH_HEADER_WORKER = "X-Worker-Token"

# --- Error Codes ---
# Error codes returned by workers in the result payload
ERROR_CODE_TRANSIENT = "TRANSIENT_ERROR"
ERROR_CODE_PERMANENT = "PERMANENT_ERROR"
ERROR_CODE_INVALID_INPUT = "INVALID_INPUT_ERROR"
ERROR_CODE_INTEGRITY_MISMATCH = "INTEGRITY_MISMATCH_ERROR"
ERROR_CODE_TIMEOUT = "TIMEOUT_ERROR"
ERROR_CODE_RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED_ERROR"
ERROR_CODE_DEPENDENCY = "DEPENDENCY_ERROR"
ERROR_CODE_SECURITY = "SECURITY_ERROR"
ERROR_CODE_INTERNAL = "INTERNAL_ERROR"

# --- Task Statuses ---
# Standard statuses for task results
TASK_STATUS_SUCCESS = "success"
TASK_STATUS_FAILURE = "failure"
TASK_STATUS_CANCELLED = "cancelled"

# --- Commands (WebSocket) ---
COMMAND_CANCEL_TASK = "cancel_task"
MSG_TYPE_PROGRESS = "progress_update"

# --- Endpoints ---
WORKER_API_PREFIX = "/_worker"

STS_TOKEN_ENDPOINT = f"{WORKER_API_PREFIX}/auth/token"
WS_ENDPOINT = f"{WORKER_API_PREFIX}/ws"

# Routes for REST API interaction
ENDPOINT_WORKER_REGISTER = f"{WORKER_API_PREFIX}/workers/register"
ENDPOINT_TASK_NEXT = f"{WORKER_API_PREFIX}/workers/{{worker_id}}/tasks/next"
ENDPOINT_TASK_RESULT = f"{WORKER_API_PREFIX}/tasks/result"
ENDPOINT_WORKER_HEARTBEAT = f"{WORKER_API_PREFIX}/workers/{{worker_id}}"

# --- Job Statuses ---
JOB_STATUS_PENDING = "pending"
JOB_STATUS_WAITING_FOR_WORKER = "waiting_for_worker"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_FINISHED = "finished"
JOB_STATUS_FAILED = "failed"
JOB_STATUS_ERROR = "error"
JOB_STATUS_QUARANTINED = "quarantined"
JOB_STATUS_CANCELLED = "cancelled"
JOB_STATUS_WAITING_FOR_HUMAN = "waiting_for_human"
JOB_STATUS_WAITING_FOR_PARALLEL = "waiting_for_parallel_tasks"
