DEFAULT_NATIVE_GAS_UNITS = 21000
GAS_BUFFER_MULTIPLIER = 1.1
ONE_GWEI = 1_000_000_000
SUGGESTED_PRIORITY_FEE_MULTIPLIER = 1.5
SUGGESTED_GAS_PRICE_MULTIPLIER = 1.5

DEFAULT_SLIPPAGE = 0.005

DEFAULT_HTTP_TIMEOUT = 30.0

ADAPTER_BALANCE = "BALANCE"
ADAPTER_BRAP = "BRAP"
ADAPTER_MOONWELL = "MOONWELL"
ADAPTER_HYPERLIQUID = "HYPERLIQUID"
ADAPTER_POOL = "POOL"
ADAPTER_TOKEN = "TOKEN"
ADAPTER_LEDGER = "LEDGER"
ADAPTER_HYPERLEND = "HYPERLEND"

DEFAULT_PAGINATION_LIMIT = 50

MANTISSA = 10**18
SECONDS_PER_YEAR = 365 * 24 * 60 * 60
MAX_UINT256 = 2**256 - 1
