"""Int subclass instances representing IDs for some predefined cutscenes and screen transitions."""

from .types.scene import Scene

SC00_OPEN_GAME_SELECT_MENU = Scene(0)
SC01_OPEN_OVERWORLD_MENU = Scene(1)
SC02_OPEN_LOCATION = Scene(2)
SC03_OPEN_SHOP_MENU = Scene(3)
SC04_OPEN_SAVE_GAME_MENU = Scene(4)
SC05_OPEN_ITEMS_MAXED_OUT_MENU = Scene(5)
SC06_UNKNOWN = Scene(6)
SC07_RUN_MENU_TUTORIAL = Scene(7)
SC08_ADD_STAR_PIECE = Scene(8)
SC09_RUN_MOLEVILLE_MOUNTAIN = Scene(9)
SC10_UNKNOWN = Scene(10)
SC11_RUN_MOLEVILLE_MOUNTAIN_INTRO = Scene(11)
SC12_UNKNOWN = Scene(12)
SC13_RUN_STAR_PIECE_END_SEQUENCE = Scene(13)
SC14_RUN_GARDEN_INTRO_SEQUENCE = Scene(14)
SC15_ENTER_GATE_TO_SMITHY_FACTORY = Scene(15)
SC16_RUN_WORLD_MAP_EVENT_SEQUENCE = Scene(16)
