from enum import Enum


class Source(Enum):
    REGISTRATION = "registration"
    CLEAR_RECYCLE_BIN = "clearrecyclebin"
    COMBINE = "combine"
    BULK_CREATE = "bulkcreate"
    CONNECTORS = "connectors"
    COPY = "copy"
    EMAIL_SEND = "emailsend"
    EVOTOR = "evotor"
    EXPORT = "export"
    EXPORT_EDICLIENT_1C = "exportediclient1c"
    IMPORT = "import"
    IMPORT_1C = "import1c"
    IMPORT_ALFABANK = "importAlfabank"
    IMPORT_MODULEBANK = "importModulebank"
    IMPORT_TINKOFFBANK = "importTinkoffbank"
    IMPORT_TOCHKABANK = "importTochkabank"
    IMPORT_EDICLIENT_1C = "importediclient1c"
    LOGIN_LOGOUT = "loginlogout"
    PHONE_1_0 = "phone-1.0"
    POS_API = "posapi"
    REMAP_1_0 = "remap-1.0"
    REMAP_1_1 = "remap-1.1"
    REMAP_1_2 = "remap-1.2"
    REST_API = "restapi"
    RETAIL = "retail"
    APP = "app"
