"""
Pydantic Models for CMDB - system/modem3g/custom

Runtime validation models for system/modem3g/custom configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any, Optional

# ============================================================================
# Enum Definitions (for fields with 4+ allowed values)
# ============================================================================


# ============================================================================
# Main Model
# ============================================================================

class CustomModel(BaseModel):
    """
    Pydantic model for system/modem3g/custom configuration.
    
    Configuration for system/modem3g/custom
    
    Validation Rules:        - id_: pattern=        - vendor: pattern=        - model: pattern=        - vendor_id: pattern=        - product_id: pattern=        - class_id: pattern=        - init_string: pattern=        - modeswitch_string: pattern=    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
        validate_assignment = True  # Validate on attribute assignment
        use_enum_values = True  # Use enum values instead of names
    
    # ========================================================================
    # Model Fields
    # ========================================================================
    
    id_: int | None = Field(default=None, serialization_alias="id", description="ID.")    
    vendor: str | None = Field(default=None, description="MODEM vendor name.")    
    model: str | None = Field(default=None, description="MODEM model name.")    
    vendor_id: str | None = Field(default=None, description="USB vendor ID in hexadecimal format (0000-ffff).")    
    product_id: str | None = Field(default=None, description="USB product ID in hexadecimal format (0000-ffff).")    
    class_id: str | None = Field(default=None, description="USB interface class in hexadecimal format (00-ff).")    
    init_string: str | None = Field(default=None, description="Init string in hexadecimal format (even length).")    
    modeswitch_string: str | None = Field(default=None, description="USB modeswitch arguments. For example: '-v 1410 -p 9030 -V 1410 -P 9032 -u 3'.")    
    # ========================================================================
    # Custom Validators
    # ========================================================================
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def to_fortios_dict(self) -> dict[str, Any]:
        """
        Convert model to FortiOS API payload format.
        
        Returns:
            Dict suitable for POST/PUT operations
        """
        # Export with exclude_none to avoid sending null values
        return self.model_dump(exclude_none=True, by_alias=True)
    
    @classmethod
    def from_fortios_response(cls, data: dict[str, Any]) -> "CustomModel":
        """
        Create model instance from FortiOS API response.
        
        Args:
            data: Response data from API
            
        Returns:
            Validated model instance
        """
        return cls(**data)

# ============================================================================
# Type Aliases for Convenience
# ============================================================================

Dict = dict[str, Any]  # For backward compatibility

# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "CustomModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-01-27T21:47:54.568138Z
# ============================================================================