from typing import Protocol


class StorageClient(Protocol):
    async def upload(self, key: str, data: bytes) -> None: ...

    async def download(self, key: str) -> bytes: ...

    async def exists(self, key: str) -> bool: ...

    async def delete(self, key: str) -> None: ...
