# coding: utf-8

"""
    SwiftyRX API

    API for the SwiftyRX Backend 

    The version of the OpenAPI document: 0.1.DEV-0
    Contact: paul.tindall@rxfoundry.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rxfoundry.clients.swifty_api.models.prescriber import Prescriber

class TestPrescriber(unittest.TestCase):
    """Prescriber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Prescriber:
        """Test Prescriber
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Prescriber`
        """
        model = Prescriber()
        if include_optional:
            return Prescriber(
                uuid = '',
                last_name = '',
                first_name = '',
                middle_name = '',
                credentials_text = '',
                npi = '',
                dea_number = '',
                practice_address = rxfoundry.clients.swifty_api.models.address.Address(
                    uuid = '', 
                    address_line_one = '', 
                    address_line_two = '', 
                    city = '', 
                    state_province = '', 
                    postal_code = '', 
                    country_code = '', 
                    longitude = 1.337, 
                    latitude = 1.337, 
                    distance = 1.337, )
            )
        else:
            return Prescriber(
        )
        """

    def testPrescriber(self):
        """Test Prescriber"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
