# coding: utf-8

"""
    User Service API

    Solomon AI User Service API - Manages user profiles and authentication

    The version of the OpenAPI document: 1.0
    Contact: yoanyomba@solomon-ai.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solomonai_backend_client_sdk.models.create_user_v2_request import CreateUserV2Request

class TestCreateUserV2Request(unittest.TestCase):
    """CreateUserV2Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUserV2Request:
        """Test CreateUserV2Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUserV2Request`
        """
        model = CreateUserV2Request()
        if include_optional:
            return CreateUserV2Request(
                supabase_auth_user_id = 'auth0|5f7d8ff9d8f1f0006f3e9f1e',
                email = 'john.doe@example.com',
                username = 'johndoe2023',
                profile_type = 'PROFILE_TYPE_UNSPECIFIED',
                profile_image_url = 'https://example.com/profile_images/johndoe.jpg',
                organization_id = '',
                tenant_id = '',
                company_name = 'Acme, Inc.',
                is_private = False
            )
        else:
            return CreateUserV2Request(
                supabase_auth_user_id = 'auth0|5f7d8ff9d8f1f0006f3e9f1e',
                username = 'johndoe2023',
                profile_type = 'PROFILE_TYPE_UNSPECIFIED',
                profile_image_url = 'https://example.com/profile_images/johndoe.jpg',
                organization_id = '',
                tenant_id = '',
                company_name = 'Acme, Inc.',
                is_private = False,
        )
        """

    def testCreateUserV2Request(self):
        """Test CreateUserV2Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
