# mitm_handle.pyi
from typing import Any

class MitmHandle:
    """Python wrapper for MitmHandle Rust implementation."""

    def __init__(self, proxyConfig: dict[str, Any], swVersion: str) -> None: ...
    def requestheaders(self, flow: Any) -> None: ...
    def request(self, flow: Any) -> None: ...
    def responseheaders(self, flow: Any) -> None: ...
    def response(self, flow: Any) -> None: ...
    def http_connect_upstream(self, flow: Any) -> None: ...
    @staticmethod
    def atob(str: str) -> str | None: ...
