"""Binary sensor entity definitions for Qube Heat Pump."""

from .base import EntityDef, InputType, Platform

_BINARY_SENSOR_DEFS: tuple[EntityDef, ...] = (
    EntityDef(
        key="dout_srcpmp_val",
        name="Source pump power supply",
        address=0,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="dout_usrpmp_val",
        name="User pump power supply",
        address=1,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="dout_fourwayvlv_val",
        name="Four-way valve control",
        address=2,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="dout_cooling_val",
        name="Cooling active output",
        address=3,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="dout_threewayvlv_val",
        name="Three-way valve output (CV/DHW)",
        address=4,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="dout_bufferpmp_val",
        name="Buffer pump output",
        address=5,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="dout_heaterstep1_val",
        name="Heater 1 output",
        address=6,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="dout_heaterstep2_val",
        name="Heater 2 output",
        address=7,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="dout_heaterstep3_val",
        name="Heater 3 output",
        address=8,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="keybonoff",
        name="Heat pump keypad status",
        address=9,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="al_maxtime_antileg_active",
        name="Alarm: Max time anti-legionella exceeded",
        address=10,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="al_maxtime_dhw_active",
        name="Alarm: Max time DHW exceeded",
        address=11,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="al_dewpoint_active",
        name="Alarm: Dewpoint activated",
        address=12,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="al_underfloorsafety_active",
        name="Alarm: Supply too hot (CV)",
        address=13,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="alrm_flw",
        name="Alarm: Flow CV",
        address=15,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="usralrms",
        name="Alarm: Collective alarm CV",
        address=16,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="coolingalrms",
        name="Alarm: Collective alarm cooling",
        address=17,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="heatingalrms",
        name="Alarm: Collective alarm heating",
        address=18,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="alarmmng_al_workinghour",
        name="Alarm: Working hours",
        address=19,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="srsalrm",
        name="Alarm: Collective alarm source",
        address=20,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="glbal",
        name="Global Alarm",
        address=21,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="alarmmng_al_pwrplus",
        name="Alarm: Collective alarm compressor",
        address=22,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="roomprb_en",
        name="Room sensor activated",
        address=23,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="plantdemand",
        name="Plant sensor demand",
        address=25,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="en_dhwpid",
        name="DHW controller enabled",
        address=26,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="plantprb_en",
        name="Plant sensor activated",
        address=27,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="bufferprb_en",
        name="Buffer sensor activated",
        address=28,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="id_demand",
        name="Digital input demand",
        address=29,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="id_summerwinter",
        name="Digital input summer mode activated",
        address=30,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="dewpoint",
        name="Digital input dewpoint activated",
        address=31,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="boostersecurity",
        name="Digital input booster activated",
        address=32,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="srcflw",
        name="Digital input source flow activated",
        address=34,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="daynightmode",
        name="Day/night mode status",
        address=37,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="thermostatdemand",
        name="Internal thermostat demand",
        address=38,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="req_antileg_1",
        name="Anti-legionella enabled",
        address=39,
        input_type=InputType.DISCRETE_INPUT,
        platform=Platform.BINARY_SENSOR,
    ),
    # Coil-based binary sensors
    EntityDef(
        key="bms_demand",
        name="Heat demand active",
        address=19,
        input_type=InputType.COIL,
        platform=Platform.BINARY_SENSOR,
    ),
    EntityDef(
        key="surplus_pv",
        name="PV surplus active",
        address=64,
        input_type=InputType.COIL,
        platform=Platform.BINARY_SENSOR,
    ),
)

# Export as dict for easy lookup by key
BINARY_SENSORS: dict[str, EntityDef] = {e.key: e for e in _BINARY_SENSOR_DEFS}
