THS = [
    ("the hundredth time", {}, "the 100th time"),
    ("the fifth time", {}, "the 5th time"),
    ("the fourth amendment", {}, "the 4th amendment"),
    ("one hundredth", {"do_simple_evals": False}, "1/100"),
    ("one hundredth", {}, "0.01"),
    ("1 hundredth", {"do_simple_evals": False}, "1/100"),
    ("1 hundredth", {}, "0.01"),
    ("1 100th", {}, "0.01"),
    ("two hundredths", {}, "0.02"),
    ("five thousandths", {}, "0.005"),
    ("five point 8 millionth", {}, "0.0000058"),
    ("one third", {}, "1/3"),
    ("a third", {}, "1/3"),
    ("two thirds", {}, "2/3"),
    ("negative 5 thirds", {}, "-5/3"),
    ("two halves", {}, "1"),
    ("half", {"do_simple_evals": False}, "1/2"),
    ("half", {}, "0.5"),
    ("one over", {}, "1 over"),
    ("one over five", {"do_simple_evals": False}, "1/5"),
    ("one over five", {}, "0.2"),
    ("two divided by three", {}, "2/3")
]