CHUTES_DIR = ".chutes"
HOTKEY_HEADER = "X-Chutes-Hotkey"
SIGNATURE_HEADER = "X-Chutes-Signature"
NONCE_HEADER = "X-Chutes-Nonce"
AUTHORIZATION_HEADER = "Authorization"
USER_ID_HEADER = "X-Chutes-UserID"
CHUTEID_HEADER = "X-Chutes-ChuteID"
FUNCTION_HEADER = "X-Chutes-Function"
