-- Copyright (c) 2026, UChicago Argonne, LLC
-- BSD OPEN SOURCE LICENSE. Full license can be found in LICENSE.md
--@ THERE IS CURRENTLY NO DOCUMENTATION FOR THIS TABLE
--@
--@

CREATE TABLE "Traveler" (
  "traveler" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "hhold" INTEGER NOT NULL DEFAULT 0,
  "person" INTEGER NOT NULL DEFAULT 0,
  "tour" INTEGER NOT NULL DEFAULT 0,
  "trip" INTEGER NOT NULL DEFAULT 0,
  "mode" INTEGER NOT NULL DEFAULT 0,
  "time" REAL NULL DEFAULT 0,
  "distance" REAL NULL DEFAULT 0,
  "speed" REAL NULL DEFAULT 0,
  "link" INTEGER NOT NULL DEFAULT 0,
  "dir" INTEGER NOT NULL DEFAULT 0,
  "lane" INTEGER NOT NULL DEFAULT 0,
  "offset" REAL NULL DEFAULT 0,
  "route" INTEGER NOT NULL DEFAULT 0)