"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .usersettings import UserSettings, UserSettingsTypedDict
from img_src.types import BaseModel
from typing_extensions import TypedDict


class SettingsResponseTypedDict(TypedDict):
    settings: UserSettingsTypedDict


class SettingsResponse(BaseModel):
    settings: UserSettings
