from aip_agents.schema.hitl import ApprovalDecisionType

__all__ = ['SYSTEM_PROMPT', 'DELEGATE_PREFIX', 'OUTPUT_EXCERPT_MAX_CHARS', 'HITL_PENDING_TITLE', 'HITL_PENDING_DESCRIPTION', 'HITL_DECISION_MESSAGES']

SYSTEM_PROMPT: str
DELEGATE_PREFIX: str
OUTPUT_EXCERPT_MAX_CHARS: int
HITL_PENDING_TITLE: str
HITL_PENDING_DESCRIPTION: str
HITL_DECISION_MESSAGES: dict[ApprovalDecisionType, tuple[str, str]]
