"""Sensor entity definitions for Qube Heat Pump."""

from .base import DataType, EntityDef, InputType, Platform

_SENSOR_DEFS: tuple[EntityDef, ...] = (
    # Holding register sensors (configuration/setpoints readable as sensors)
    EntityDef(
        key="thermostat_heatsetp_day",
        name="Room setpoint heating (day)",
        address=27,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="thermostat_heatsetp_night",
        name="Room setpoint heating (night)",
        address=29,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="thermostat_coolsetp_day",
        name="Room setpoint cooling (day)",
        address=31,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="thermostat_coolsetp_night",
        name="Room setpoint cooling (night)",
        address=33,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="tapw_timeprogram_dt_bms",
        name="dT flow temperature DHW",
        address=43,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.INT16,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="tapw_timeprogram_dhws",
        name="Minimum temperature DHW",
        address=44,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="tapw_timeprogram_dhws_prog",
        name="DHW temperature (active program)",
        address=46,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="regulation_buffersetp_min",
        name="Minimum setpoint buffer regulation",
        address=99,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="usr_pid_heatsetp",
        name="Heat setpoint (no curve)",
        address=101,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="usr_pid_coolsetp",
        name="Cooling setpoint (no curve)",
        address=103,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="regulation_buffersetp_max",
        name="Max buffer setpoint (cooling)",
        address=169,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="tapw_timeprogram_dhwsetp_nolinq",
        name="User-defined DHW setpoint",
        address=173,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
        writable=True,  # This setpoint can be written via Modbus
    ),
    # Input register sensors (read-only)
    EntityDef(
        key="aout_usrpmp_val",
        name="User (CV) pump control %",
        address=4,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="%",
        scale=100.0,
    ),
    EntityDef(
        key="aout_srcpmp_val",
        name="Source pump control %",
        address=6,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="%",
        scale=100.0,
    ),
    EntityDef(
        key="aout_srcvalve_val",
        name="Source valve control %",
        address=8,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="%",
        scale=100.0,
    ),
    EntityDef(
        key="dhw_regreq",
        name="DHW regulation demand %",
        address=14,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="%",
        scale=100.0,
    ),
    EntityDef(
        key="comppwrreq",
        name="Compressor demand %",
        address=16,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="%",
        scale=100.0,
    ),
    EntityDef(
        key="flow",
        name="Measured Flow",
        address=18,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="L/min",
    ),
    # Core temperature sensors (mapped to QubeState typed fields)
    EntityDef(
        key="temp_supply",
        name="Supply temperature CV",
        address=20,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="temp_return",
        name="Return temperature CV",
        address=22,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="temp_source_in",
        name="Source temperature from roof",
        address=24,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="temp_source_out",
        name="Source temperature to roof",
        address=26,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="temp_room",
        name="Room temperature",
        address=28,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="temp_dhw",
        name="DHW temperature",
        address=30,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="temp_outside",
        name="Outside temperature",
        address=32,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="cop_calc",
        name="COP (calculated)",
        address=34,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
    ),
    EntityDef(
        key="power_thermic",
        name="Current power",
        address=36,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="W",
    ),
    EntityDef(
        key="status_code",
        name="Status code",
        address=38,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.UINT16,
        platform=Platform.SENSOR,
    ),
    EntityDef(
        key="regsetp",
        name="Calculated heat pump setpoint",
        address=39,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="coolsetp_1",
        name="Cooling setpoint",
        address=41,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="heatsetp_1",
        name="Heating setpoint",
        address=43,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="compressor_speed",
        name="Current compressor speed",
        address=45,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="rpm",
        scale=60.0,
    ),
    EntityDef(
        key="dhw_setp",
        name="DHW calculated setpoint",
        address=47,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="workinghours_dhw_hrsret",
        name="Working hours DHW",
        address=50,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.INT16,
        platform=Platform.SENSOR,
        unit="h",
    ),
    EntityDef(
        key="workinghours_heat_hrsret",
        name="Working hours heating",
        address=52,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.INT16,
        platform=Platform.SENSOR,
        unit="h",
    ),
    EntityDef(
        key="workinghours_cool_hrsret",
        name="Working hours cooling",
        address=54,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.INT16,
        platform=Platform.SENSOR,
        unit="h",
    ),
    EntityDef(
        key="workinghours_heater1_hrs",
        name="Working hours heater 1",
        address=56,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.INT16,
        platform=Platform.SENSOR,
        unit="h",
    ),
    EntityDef(
        key="workinghours_heater2_hrs",
        name="Working hours heater 2",
        address=58,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.INT16,
        platform=Platform.SENSOR,
        unit="h",
    ),
    EntityDef(
        key="workinghours_heater3_hrs",
        name="Working hours heater 3",
        address=60,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.INT16,
        platform=Platform.SENSOR,
        unit="h",
    ),
    EntityDef(
        key="power_electric",
        name="Total electric power (calculated)",
        address=61,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="W",
    ),
    EntityDef(
        key="plantsetp",
        name="Plant regulation setpoint",
        address=65,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="energy_total_electric",
        name="Total electric consumption (excl. standby)",
        address=69,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="kWh",
    ),
    EntityDef(
        key="energy_total_thermic",
        name="Total thermic yield",
        address=71,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="kWh",
    ),
    EntityDef(
        key="modbus_roomtemp",
        name="Linq room temperature",
        address=75,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    # Aliases for QubeState compatibility (same addresses as core sensors)
    EntityDef(
        key="flow_rate",
        name="Flow rate",
        address=18,
        input_type=InputType.INPUT_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="L/min",
    ),
    EntityDef(
        key="setpoint_room_heat_day",
        name="Room setpoint heating (day)",
        address=27,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="setpoint_room_heat_night",
        name="Room setpoint heating (night)",
        address=29,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="setpoint_room_cool_day",
        name="Room setpoint cooling (day)",
        address=31,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="setpoint_room_cool_night",
        name="Room setpoint cooling (night)",
        address=33,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
    ),
    EntityDef(
        key="setpoint_dhw",
        name="User-defined DHW setpoint",
        address=173,
        input_type=InputType.HOLDING_REGISTER,
        data_type=DataType.FLOAT32,
        platform=Platform.SENSOR,
        unit="°C",
        writable=True,
    ),
)

# Export as dict for easy lookup by key
SENSORS: dict[str, EntityDef] = {e.key: e for e in _SENSOR_DEFS}
