# coding: utf-8

"""
    User Service API

    Solomon AI User Service API - Manages user profiles and authentication

    The version of the OpenAPI document: 1.0
    Contact: yoanyomba@solomon-ai.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ScopeType(str, Enum):
    """
     - SCOPE_TYPE_UNSPECIFIED: Default unspecified scope.  - SCOPE_TYPE_READ: Read-only access to resources.  - SCOPE_TYPE_WRITE: Write access to resources.  - SCOPE_TYPE_DELETE: Delete access to resources.  - SCOPE_TYPE_ADMIN: Full administrative access.  - SCOPE_TYPE_USER_READ: Read-only access to user resources.  - SCOPE_TYPE_USER_WRITE: Write access to user resources.  - SCOPE_TYPE_TEAM_READ: Read-only access to team resources.  - SCOPE_TYPE_TEAM_WRITE: Write access to team resources.  - SCOPE_TYPE_BILLING: Access to billing and payment resources.  - SCOPE_TYPE_ANALYTICS: Access to analytics and reporting.
    """

    """
    allowed enum values
    """
    SCOPE_TYPE_UNSPECIFIED = 'SCOPE_TYPE_UNSPECIFIED'
    SCOPE_TYPE_READ = 'SCOPE_TYPE_READ'
    SCOPE_TYPE_WRITE = 'SCOPE_TYPE_WRITE'
    SCOPE_TYPE_DELETE = 'SCOPE_TYPE_DELETE'
    SCOPE_TYPE_ADMIN = 'SCOPE_TYPE_ADMIN'
    SCOPE_TYPE_USER_READ = 'SCOPE_TYPE_USER_READ'
    SCOPE_TYPE_USER_WRITE = 'SCOPE_TYPE_USER_WRITE'
    SCOPE_TYPE_TEAM_READ = 'SCOPE_TYPE_TEAM_READ'
    SCOPE_TYPE_TEAM_WRITE = 'SCOPE_TYPE_TEAM_WRITE'
    SCOPE_TYPE_BILLING = 'SCOPE_TYPE_BILLING'
    SCOPE_TYPE_ANALYTICS = 'SCOPE_TYPE_ANALYTICS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ScopeType from a JSON string"""
        return cls(json.loads(json_str))


