"""
JavaScript Date builtin module.

Usage:

```python
from pulse.js import Date
Date()                        # -> new Date()
Date.now()                    # -> Date.now()
Date.parse("2023-01-01")      # -> Date.parse("2023-01-01")

# Or import from module directly:
from pulse.js.date import Date
```
"""

from typing import Any as _Any

from pulse.transpiler.js_module import JsModule


class Date:
	"""Class for JavaScript Date instances."""

	def __init__(self, value: int | str | None = None, /): ...

	@staticmethod
	def now() -> float: ...

	@staticmethod
	def parse(dateString: str) -> float: ...

	@staticmethod
	def UTC(
		year: int,
		month: int,
		date: int | None = None,
		hours: int | None = None,
		minutes: int | None = None,
		seconds: int | None = None,
		ms: int | None = None,
		/,
	) -> float: ...

	def getDate(self) -> int: ...
	def getDay(self) -> int: ...
	def getFullYear(self) -> int: ...
	def getHours(self) -> int: ...
	def getMilliseconds(self) -> int: ...
	def getMinutes(self) -> int: ...
	def getMonth(self) -> int: ...
	def getSeconds(self) -> int: ...
	def getTime(self) -> float: ...
	def getTimezoneOffset(self) -> int: ...
	def getUTCDate(self) -> int: ...
	def getUTCDay(self) -> int: ...
	def getUTCFullYear(self) -> int: ...
	def getUTCHours(self) -> int: ...
	def getUTCMilliseconds(self) -> int: ...
	def getUTCMinutes(self) -> int: ...
	def getUTCMonth(self) -> int: ...
	def getUTCSeconds(self) -> int: ...
	def setDate(self, date: int) -> float: ...
	def setFullYear(
		self, year: int, month: int | None = None, date: int | None = None, /
	) -> float: ...
	def setHours(
		self,
		hours: int,
		min: int | None = None,
		sec: int | None = None,
		ms: int | None = None,
		/,
	) -> float: ...
	def setMilliseconds(self, ms: int) -> float: ...
	def setMinutes(
		self, min: int, sec: int | None = None, ms: int | None = None, /
	) -> float: ...
	def setMonth(self, month: int, date: int | None = None, /) -> float: ...
	def setSeconds(self, sec: int, ms: int | None = None, /) -> float: ...
	def setTime(self, time: float) -> float: ...
	def setUTCDate(self, date: int) -> float: ...
	def setUTCFullYear(
		self, year: int, month: int | None = None, date: int | None = None
	) -> float: ...
	def setUTCHours(
		self,
		hours: int,
		min: int | None = None,
		sec: int | None = None,
		ms: int | None = None,
		/,
	) -> float: ...
	def setUTCMilliseconds(self, ms: int) -> float: ...
	def setUTCMinutes(
		self, min: int, sec: int | None = None, ms: int | None = None, /
	) -> float: ...
	def setUTCMonth(self, month: int, date: int | None = None, /) -> float: ...
	def setUTCSeconds(self, sec: int, ms: int | None = None, /) -> float: ...
	def toDateString(self) -> str: ...
	def toISOString(self) -> str: ...
	def toJSON(self, key: _Any | None = None, /) -> str: ...
	def toLocaleDateString(
		self, locales: str | None = None, options: _Any | None = None, /
	) -> str: ...
	def toLocaleString(
		self, locales: str | None = None, options: _Any | None = None, /
	) -> str: ...
	def toLocaleTimeString(
		self, locales: str | None = None, options: _Any | None = None, /
	) -> str: ...
	def toString(self) -> str: ...
	def toTimeString(self) -> str: ...
	def toUTCString(self) -> str: ...
	def valueOf(self) -> float: ...


# Self-register this module as a JS builtin (global identifier)
JsModule.register(name=None)
