# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Odoo Implementation",
    "version": "14.0.5.22.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_terminate_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_ready_mixin",
        "ssi_transaction_partner_mixin",
        "ssi_task_mixin",
        "web_widget_ckeditor",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/ir_module_category/odoo_change_request.xml",
        "security/ir_module_category/odoo_configuration_change_record.xml",
        "security/ir_module_category/odoo_use_case_specification.xml",
        "security/res_group_data.xml",
        "security/res_groups/odoo_change_request.xml",
        "security/res_groups/odoo_configuration_change_record.xml",
        "security/res_groups/odoo_use_case_specification.xml",
        "security/ir.model.access.csv",
        "security/ir_model_access/odoo_change_request.xml",
        "security/ir_model_access/odoo_configuration_change_record.xml",
        "security/ir_model_access/odoo_use_case_specification.xml",
        "security/ir_rule/odoo_change_request.xml",
        "security/ir_rule/odoo_configuration_change_record.xml",
        "security/ir_rule/odoo_use_case_specification.xml",
        "menu.xml",
        "ir_sequence/odoo_implementation.xml",
        "ir_sequence/odoo_deployment.xml",
        "ir_sequence/odoo_feature_implementation.xml",
        "ir_sequence/odoo_feature_issue.xml",
        "ir_sequence/odoo_change_request.xml",
        "ir_sequence/odoo_configuration_change_record.xml",
        "ir_sequence/odoo_use_case_specification.xml",
        "data/sequence_template_data.xml",
        "sequence_template/odoo_change_request.xml",
        "sequence_template/odoo_configuration_change_record.xml",
        "sequence_template/odoo_use_case_specification.xml",
        "data/policy_template_data.xml",
        "policy_template/odoo_change_request.xml",
        "policy_template/odoo_configuration_change_record.xml",
        "policy_template/odoo_use_case_specification.xml",
        "data/approval_template_data.xml",
        "approval_template/odoo_change_request.xml",
        "approval_template/odoo_configuration_change_record.xml",
        "approval_template/odoo_use_case_specification.xml",
        "views/odoo_version_views.xml",
        "views/odoo_feature_views.xml",
        "views/odoo_feature_category_views.xml",
        "views/odoo_environment_views.xml",
        "views/odoo_deployment_views.xml",
        "views/odoo_implementation_views.xml",
        "views/odoo_feature_implementation_views.xml",
        "views/odoo_use_case_views.xml",
        "views/odoo_feature_issue_views.xml",
        "views/odoo_module_views.xml",
        "views/odoo_website_theme_views.xml",
        "views/odoo_additional_functionality_views.xml",
        "views/odoo_feature_additional_functionality_views.xml",
        "views/odoo_change_request.xml",
        "views/odoo_configuration_record_change.xml",
        "views/odoo_use_case_specification.xml",
    ],
    "demo": [],
}
