# coding: utf-8

"""
    Go DMN Web API

    API for the Go DMN Web application.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantumdmn.models.kpi_trend_data_inner import KpiTrendDataInner

class TestKpiTrendDataInner(unittest.TestCase):
    """KpiTrendDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KpiTrendDataInner:
        """Test KpiTrendDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KpiTrendDataInner`
        """
        model = KpiTrendDataInner()
        if include_optional:
            return KpiTrendDataInner(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                value = 1.337
            )
        else:
            return KpiTrendDataInner(
        )
        """

    def testKpiTrendDataInner(self):
        """Test KpiTrendDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
