# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nominal.public_app.authentication.v1 import public_app_authentication_pb2 as nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nominal/public_app/authentication/v1/public_app_authentication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PublicAppAuthenticationServiceStub(object):
    """Authentication intended for public applications developed by Nominal.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/nominal.public_app.authentication.v1.PublicAppAuthenticationService/HealthCheck',
                request_serializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetOidcInit = channel.unary_unary(
                '/nominal.public_app.authentication.v1.PublicAppAuthenticationService/GetOidcInit',
                request_serializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.GetOidcInitRequest.SerializeToString,
                response_deserializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.GetOidcInitResponse.FromString,
                _registered_method=True)
        self.ExchangeAuthorizationCode = channel.unary_unary(
                '/nominal.public_app.authentication.v1.PublicAppAuthenticationService/ExchangeAuthorizationCode',
                request_serializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.ExchangeAuthorizationCodeRequest.SerializeToString,
                response_deserializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.ExchangeAuthorizationCodeResponse.FromString,
                _registered_method=True)


class PublicAppAuthenticationServiceServicer(object):
    """Authentication intended for public applications developed by Nominal.
    """

    def HealthCheck(self, request, context):
        """Allows public applications to check compatibility with the target service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOidcInit(self, request, context):
        """Allows public applications to obtain credentials used to initiate a user authentication flow using OIDC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeAuthorizationCode(self, request, context):
        """Performs the authorization code exchange from OIDC on behalf of the client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublicAppAuthenticationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.HealthCheckRequest.FromString,
                    response_serializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetOidcInit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOidcInit,
                    request_deserializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.GetOidcInitRequest.FromString,
                    response_serializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.GetOidcInitResponse.SerializeToString,
            ),
            'ExchangeAuthorizationCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeAuthorizationCode,
                    request_deserializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.ExchangeAuthorizationCodeRequest.FromString,
                    response_serializer=nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.ExchangeAuthorizationCodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nominal.public_app.authentication.v1.PublicAppAuthenticationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nominal.public_app.authentication.v1.PublicAppAuthenticationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PublicAppAuthenticationService(object):
    """Authentication intended for public applications developed by Nominal.
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nominal.public_app.authentication.v1.PublicAppAuthenticationService/HealthCheck',
            nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.HealthCheckRequest.SerializeToString,
            nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOidcInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nominal.public_app.authentication.v1.PublicAppAuthenticationService/GetOidcInit',
            nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.GetOidcInitRequest.SerializeToString,
            nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.GetOidcInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeAuthorizationCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nominal.public_app.authentication.v1.PublicAppAuthenticationService/ExchangeAuthorizationCode',
            nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.ExchangeAuthorizationCodeRequest.SerializeToString,
            nominal_dot_public__app_dot_authentication_dot_v1_dot_public__app__authentication__pb2.ExchangeAuthorizationCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
