let k={},m=[],aa=null,ba,ca={},n=[],da=[],ea=[],fa=[];function q(a){return a?document.createTextNode(a):null}function ia(){let a=r("input");a.type="file";a.id="file";return a}function ja(a,b){a=a.className.split(" ");for(let c=0;c<a.length;++c)if(a[c]==b)return!0;return!1}function ka(a,b){return b?2==b?n[a+8]:3==b?"DC Out"+(a-8+1):da[a]?da[a]:8>a?"Port"+(a+1):10<=a?"Port"+(a-2+1):"SFP+"+(a-8+1):n[a]}function r(a,b){return u(document.createElement(a),q(b))}
function v(a,b,c){a=r(a,c);b&&(a.className=b);return a}function u(a,b){b&&a.appendChild(b);return a}function la(a){var b=q("\ud83d\udd34 A backup version of SwOS is running, update SwOS for full functionality.");b&&a.prepend(b)}function w(a){return document.getElementById(a)}function x(a,b,c){c=v("td",c);b&&(c.colSpan=b);return u(c,a)}
function ma(a,b){for(var c=0;c<a.length-1&&"0"==a.charAt(c);)++c;a=a.substring(c);c=parseInt(a,b);return isNaN(c)?c:c.toString(b).toLowerCase()!=a.toLowerCase()?Number.NaN:c}function oa(a){return a.toString(16).padStart(2,"0")}function pa(a){let b=[];for(var c=0;256>c;++c)b[c]=c;let e=0,d=0;for(d=0;256>d;++d)e=e+a.charCodeAt(d%a.length)+b[d]&255,c=b[d],b[d]=b[e],b[e]=c;d=e=0;b.ta=function(){d=d+1&255;e=e+b[d]&255;let f=b[d];b[d]=b[e];b[e]=f;return b[b[d]+b[e]&255]};return b}
function qa(a,b){let c=[];for(var e=0;e<b.length;++e)c.push(b.charCodeAt(e));c.push(0);for(e=0;e<a.length;++e)c.push(a.charCodeAt(e));for(;32>c.length;)c.push(0);for(""==b&&(b="*");16>b.length;)b+=b;b=b.substring(0,16);a=pa(b);for(b=0;64>b;++b)c[b&31]^=a.ta();a="";for(b=0;32>b;++b)a+=oa(c[b]);return a}let ra=!1;function sa(a,b,c){a||(a=w("status"),ra=!1);a.className=c;a.role="";a.innerHTML!=b&&(a.innerHTML=b,a.role="alert")}function ta(a){sa(a,"","status empty")}
function y(a,b){sa(a,b,"status notify")}function z(a,b){sa(a,"ERROR:\u00a0"+b,"status error")}function ua(a,b){a||=w("status");let c=a.innerHTML,e=a.className;c!=b&&(y(a,b),setTimeout(function(){a.innerHTML==b&&(a.innerHTML=c,a.className=e)},2E3))}function va(a,b){sa(a,b,"status important")}
function A(a,b,c,e){if(b){for(var d=0;d<a.J.length;++d)if(a.J[d].wa==b){a.J.splice(d,1);break}c&&a.J.unshift({wa:b,name:e})}if(a.unique){b={};c=!1;e=document.getElementsByName(a.unique.id);for(d=0;d<e.length;++d){let f=e[d];if("error"==f.className)continue;f.className="";let g=f.value;b[g]?(f.className="dup",b[g].className="dup",c=!0):(f.className="",b[g]=f)}b=c}else b=!1;a.$=b;0!=a.J.length||a.$?(0<a.J.length?z(a.status,'Invalid "'+a.J[0].name+'"'):z(a.status,'Duplicate "'+a.fa+'"'),a.G&&(a.G.disabled=
!0),a.K=!0):a.Y||(y(a.status,"Pending changes"),a.G&&(a.G.disabled=!1),a.K=!0);if(a.K&&a.h.onchange)a.h.onchange(a)}function wa(a){a.J=[];a.$=!1;a.G&&(a.G.disabled=!0);ta(a.status);a.K=!1;a.h.ya&&a.h.ya(a)}function B(a){let b=r("input");b.type="text";a&&(b.size=a);return b}function xa(a){let b=r("input");b.type="password";b.id=a;return b}function C(a,b,c){a=v("span",b.t!=C||b.o?"ro":"ro number");a.id=b.id+c;return a}
C.v=function(a,b,c,e){let d=b[a.id];if(a.M){if(b[a.id]=d>>1,d&=1,a.N){let f=b[a.N];b[a.N]=f>>1;d|=(f&1)<<1}}else d&&"object"==typeof d&&(d=d.shift());a.H&&((b=b[a.H])&&"object"==typeof b&&(b=b.shift()),d+=4294967296*b);a.o&&(d=a.ja&&void 0==a.o[d]?a.ja[d]:a.o[d]);a.scale&&(d/=a.scale);a.j&&(1E9<d?d=Math.round(d/1E9*100)/100+"G":1E6<d?d=Math.round(d/1E6*100)/100+"M":1E3<d?d=Math.round(d/1E3*100)/100+"k":d=Math.round(d));void 0==d&&(d=a.i);void 0===d||""===d?d="\u00a0":a.scale||a.j||a.o||(d=d.toLocaleString("lv"));
d=d.toString();a.w&&(d=d.padEnd(a.w,"\u00a0"));c[e]=d;return 1};C.s=function(){return 1};
function D(a,b,c){if(b.g)return C(a,b,c);let e=r("input");e.type=b.na?"radio":"checkbox";e.id=b.id+c;e.name=b.id;e.checked=b.i||0;e.value=c;e.onclick=function(){A(a);if(b.onclick)b.onclick()};e.ondblclick=function(){if(b.C){var f=e.closest("td").childNodes,g=!f[c].firstChild.checked;for(const l of f)f=l.firstChild,f.disabled||(f.checked=g);A(a)}};const d=v("span","tt");d.append(e);if(b.C){const f=ka(c);u(d,r("label",f));e.ariaLabel=`${f} ${b.n}`}b.na||(e.onmousedown=function(f){A(a);e.checked=!e.checked;
if(b.onclick)b.onclick();let g=f.pageX,l=f.pageY,h=e.checked,t;document.body.onmousemove=function(p){if(p.buttons&1){var H=p.pageX,L=p.pageY;if(null!=t){t?L=l:H=g;p=g;var K=l,M=L;L=b.onclick;p>H&&([H,p]=[p,H]);K>M&&([M,K]=[K,M]);var X=K;K=H;H=M;p>K&&([K,p]=[p,K]);X>H&&([H,X]=[X,H]);let $a=new Set;for(;X<=H;){for(M=p;M<=K;){let ha=document.elementFromPoint(M,X);ha&&"INPUT"==ha.nodeName&&"checkbox"==ha.type&&!ha.disabled&&$a.add(ha);M+=5}X+=5}p=$a;if(p.size){for(var na of p)na.checked=h;L&&L();A(a)}}else if(na=
Math.abs(g-p.pageX),L=Math.abs(l-p.pageY),10<na||10<L)t=na>L}};document.body.onmouseup=function(){t=document.body.onmousemove=null};e.onclick=function(p){p.preventDefault()}});return d}D.v=function(a,b,c,e,d){let f=b[a.id];void 0==f&&(f=a.i||0);c[e]=a.g?a.o?a.o[f&1]:f&1?ka(d)+" ":"":f&1;b[a.id]=f>>1;return 1};D.s=function(a,b,c,e){b[a.id]=(b[a.id]||0)>>1&2147483647|(c[e]?1<<a.l-1:0);return 1};function ya(a,b,c){a=v("span","ro");a.id=b.id+c;return a}
ya.v=function(a,b,c,e){(b=b[a.id])&&b.length&&(b=b.shift());b||=0;let d="";for(let f=a.I-1;0<=f;--f){let g=b>>a.ga*f&(1<<a.ga)-1;void 0!=a.u[g]&&(d+="<span title="+a.va[g]+">"+a.u[g]+"</span>")}c[e]=d;return 1};ya.s=function(){return 1};function E(a,b,c){let e=r("select");e.id=b.id+c;for(let d in b.u)u(e,r("option",b.u[d]));b.i&&(e.selectedIndex=b.i);e.onchange=function(){A(a);if(b.onchange)b.onchange()};return e}E.v=function(a,b,c,e){a=b[a.id];c[e]=void 0==a?0:a.length?a.shift():a;return 1};
E.s=function(a,b,c,e){a=a.id;c=c[e];-1==c&&(c=0);void 0==b[a]?b[a]=c:(b[a].length||(b[a]=[b[a]]),b[a].push(c));return 1};function F(a,b,c){if(b.g)return C(a,b,c);a=B(b.I||4);a.id=b.id+c;a.name=b.id;b.m&&(a.value=b.i||0);return a}
F.v=function(a,b,c,e){(b=b[a.id])&&b.length&&(b=b.shift());b||=0;let d="";if(a.m||b!=(a.i||0))a.scale&&(b/=a.scale),a.ia?(b=Math.log(b)/Math.log(10)*10,b=Math.floor(1E3*b)/1E3):a.scale&&!a.g&&(b=Math.round(b)),d=b.toString(a.O||10),a.j&&(1E9<b&&0==b%1E9?d=b/1E9+"G":1E6<b&&0==b%1E6?d=b/1E6+"M":1E3<d&&0==d%1E3&&(d=b/1E3+"k"));""!=d&&a.width&&(d=d.padStart(a.width,"0"));""!=d&&a.B&&(d+=a.B);c[e]=d;return 1};
F.s=function(a,b,c,e){if(a.g)return 1;c=c[e];var d=a.i||0;a.m&&0==c.length&&(c=d.toString());if(0!=c.length){e=1;a.j&&(d=c.charAt(c.length-1).toLowerCase(),"k"==d?e=1E3:"m"==d?e=1E6:"g"==d?e=1E9:d=null,d&&(c=c.substring(0,c.length-1)));d=ma(c,a.O||10);if(isNaN(d))return 0;d*=e;a.scale&&(d*=a.scale);if(a.max&&d>a.max||a.min&&d<a.min||0>d)return 0}void 0==b[a.id]?b[a.id]=d:(b[a.id].length||(b[a.id]=[b[a.id]]),b[a.id].push(d));return 1};
function za(a,b,c){if(b.g)return C(a,b,c);a=B(b.I||4);a.id=b.id+c;a.name=b.id;b.m&&(a.value=b.i||0);return a}za.v=function(a,b,c,e){(b=b[a.id])&&b.length&&(b=b.shift());b||=0;var d=65535;let f=32768;a.pa&&(b=a.pa(b));if(a.da)switch(a.da){case 8:d=255;f=128;break;case 32:d=4294967295,f=2147483648}b>d&&(b&=d);b>=f&&(b-=d+1);d="";if(a.m||b!=(a.i||0))a.scale&&(b/=a.scale),d=b.toString(a.O||10);""!=d&&a.B&&(d+=a.B);c[e]=d;return 1};
za.s=function(a,b,c,e){if(a.g)return 1;e=c[e];if(isNaN(e))return 0;c=a.i||0;a.m&&0==e.length&&(e=c.toString());0!=e.length&&(c=a.Ba?parseFloat(e):parseInt(e,a.O||10));if(a.i!=c&&(a.max&&c>a.max||a.min&&c<a.min))return 0;a.scale&&(c*=a.scale);c=Math.round(c);e=65535;if(a.da)switch(a.da){case 8:e=255;break;case 32:e=4294967295}0>c&&(c+=e+1);c&=e;void 0==b[a.id]?b[a.id]=c:(b[a.id].length||(b[a.id]=[b[a.id]]),b[a.id].push(c));return 1};
function G(a,b,c){if(b.g)return C(a,b,c);a=B();c=[];G.v(b,{},c,0);a.value=c[0];return a}G.v=function(a,b,c,e){b=b[a.id];b instanceof Array&&(b=b.shift());if(!b||12!=b.length||b==(a.i||"0").toString().repeat(12)){if(void 0==a.V)return c[e]="",1;b=(a.i||"0").toString().repeat(12)}a="";for(let d=0;12>d;d+=2)0<d&&(a+=":"),a+=b.substring(d,d+2);c[e]=a;return 1};
G.s=function(a,b,c,e){if(a.g)return 1;c=c[e];if(0==c.length)return a.i&&(b[a.id]=a.i.toString().repeat(12)),1;e=[];let d=0;for(var f=!1;d<c.length;)if(isNaN(parseInt(c.charAt(d),16)))if(" "==c.charAt(d))++d;else if(":"==c.charAt(d)){if(!f)return 0;f=!1;++d}else return 0;else f=1,d+1<c.length&&!isNaN(parseInt(c.charAt(d+1),16))&&(f=2),e.push(parseInt(c.substring(d,d+f),16)),d+=f,f=!0;if(6!=e.length)return 0;c=e.map(oa).join("");if(void 0!=a.V&&c==a.V.toString().repeat(12))return 0;b[a.id]=c;return 1};
function I(a,b,c){if(b.g)return C(a,b,c);a=B();a.id=b.id+c;return a}I.v=function(a,b,c,e){a=b[a.id]||0;b="";if(0!=a)for(let d=0;4>d;++d)0<d&&(b+="."),b+=a&255,a>>=8;c[e]=b;return 1};I.s=function(a,b,c,e){c=c[e];if(0==c.length)return b[a.id]=0,1;c=c.split(".");if(1==c.length)return 0;2>=c.length&&c.splice(c.length-1,0,"0");3>=c.length&&c.splice(2,0,"0");if(4!=c.length)return 0;e=0;for(let d=0;d<c.length;++d){let f=ma(c[d],10);if(isNaN(f)||0>f||255<f)return 0;e=e>>8&16777215|f<<24}b[a.id]=e;return 1};
function J(a,b,c){if(b.g)return C(a,b,c);a=B(16);a.id=b.id+c;return a}function Aa(a){let b="";for(let c=0;c+1<a.length;c+=2){let e=parseInt(a.substring(c,c+2),16);if(!e)break;b+=String.fromCharCode(e)}return b}J.v=function(a,b,c,e){b=b[a.id];b instanceof Array&&(b=b.shift());b=Aa(b);a.za&&(b=b.replace(/{(\w+)}/,function(d,f){return parseInt(f,16)}));c[e]=b;return 1};
J.s=function(a,b,c,e){if(a.g)return 1;c=c[e];if(c.length>(a.W||15))return 0;e="";for(let d=0;d<c.length;++d)e+=oa(c.charCodeAt(d));void 0==b[a.id]?b[a.id]=e:(b[a.id]instanceof Array||(b[a.id]=[b[a.id]]),b[a.id].push(e));return 1};function Ba(a,b,c){return C(a,b,c)}Ba.v=function(a,b,c,e){b=Math.floor((b[a.id]||0)/a.scale);a=(new Date(1E3*b)).toISOString().substring(11,19);b=Math.floor(b/86400);c[e]=b?b+" days "+a:a;return 1};Ba.s=function(){return 1};
function N(a,b,c){let e=r("span");for(let d=0;d<b.j.length;++d)u(e,b.j[d].t(a,b.j[d],c));return e}N.v=function(a,b,c,e){let d=0;for(let f in a.j)d+=a.j[f].t.v(a.j[f],b,c,e+d);return d};N.s=function(a,b,c,e){let d=0;for(let f in a.j){let g=a.j[f].t.s(a.j[f],b,c,e+d);if(0==g)return 0;d+=g}return d};N.I=function(a){return a.j.length};function O(a,b,c){if(b.g)return C(a,b,c);for(a=B();b.a;)b=b.a[0];a.id=b.id+c;return a}
O.v=function(a,b,c,e){let d="",f=[];for(let g in a.a){0<g&&(d+=a.D);if(0==a.a[g].t.v(a.a[g],b,f,0))return 0;d+=f[0]}b=d.lastIndexOf(a.D);b+a.D.length==d.length&&(d=d.substring(0,b));c[e]=d;return 1};O.s=function(a,b,c,e){if(a.g)return 1;c=c[e].split(a.D,a.a.length);for(e=0;e<c.length;++e)if(0==a.a[e].t.s(a.a[e],b,c,e))return 0;for(c=c.length;c<a.a.length;++c)if(0==a.a[c].t.s(a.a[c],b,[""],0))return 0;return 1};
function P(a,b,c){if(a.h.sa&&"TABLE"==b.nodeName){b=b.rows;for(var e=b.length;0<e&&"interlive"!=b[e-1].className;)--e;for(var d=0;d<e&&"interlive"!=b[d].className;)++d;let f=b[d].cells.length;for(let g=1;g<f;++g)for(let l=d;l<e;++l)P(a,b[l].cells[g],c)}else for(e=0;e<b.childNodes.length;++e){d=b.childNodes[e];if("INPUT"==d.nodeName){if("file"==d.type)continue;"text"==d.type?c(d,"value",!0):c(d,"checked",!1)}else"SELECT"==d.nodeName?c(d,"selectedIndex",!1):"SPAN"==d.nodeName&&ja(d,"ro")&&c(d,null,
!1);P(a,d,c)}}function Q(a,b,c){for(let e=0;e<a.length;++e){let d=a[e];if("string"==typeof d.t)b&&c(d,0);else for(let f=0;f<d.l;++f)c(d,f)}}function Ca(a,b,c,e){c||(c=a.table);a.Y=!0;let d=0;P(a,c,function(f,g){if(!e||!g)if(!g||f[g]!=b[d])if(f[g||"innerHTML"]=b[d],f.onchange)f.onchange(null);++d});a.Y=!1}function Da(a,b){b||(b=a.table);let c=[];P(a,b,function(e,d){c.push(d?e[d]:null)});return c}function Ea(a,b){b=0==b.t.s(b,{},[a.value],0);a.className=b?"error":"";return b}
function Fa(a,b,c){A(a,b,Ea(b,c),c.n)}function Ga(a,b,c){let e=b.value;b.onkeydown=function(){setTimeout(function(){e!=b.value&&(e=b.value,Fa(a,b,c))},1)};b.onchange=function(){e=b.value;Fa(a,b,c)};b.oncut=function(){e=b.value;Fa(a,b,c)};b.onpaste=function(){e=b.value;Fa(a,b,c)};b.ondrop=function(){e=b.value;Fa(a,b,c)};b.oninput=function(){e=b.value;Fa(a,b,c)};Ea(b,c)}
function Ha(a,b,c){let e=[];P(a,b,function(f,g,l){e.push(l?f:null)});let d=0;Q(c,!1,function(f){e[d]&&Ga(a,e[d],f);d+=f.t.I?f.t.I(f):1})}function Ia(a,b){let c=b?"[":"{",e=!0;for(let f in a){var d=a[f];e||(c+=",");e=!1;b||(c+=f+":");switch(typeof d){case "string":c+="'"+d+"'";break;case "number":d=(d>>4&268435455).toString(16)+(d&15).toString(16);1==(d.length&1)&&(d="0"+d);c+="0x"+d;break;case "object":d&&(c+=Ia(d,!0));break;default:c+="x"}}return c+(b?"]":"}")}
function Ja(a){return`[${a.map(b=>Ia(b)).join()}]`}function Ka(a,b,c){let e=new XMLHttpRequest;e.onreadystatechange=function(){4==e.readyState&&c(e.status)};e.open("POST",a,!0);e.setRequestHeader("Content-Type","text/plain");e.send(b)}function La(a,b){let c=[],e=0;Q(a,!1,function(d,f){e+=d.t.v(d,b,c,e,f)});return c}function Ma(a,b){let c=0,e={};try{Q(a,!1,function(d){let f=d.t.s(d,e,b,c);if(0==f)throw d;c+=f})}catch(d){return null}return e}
function Na(a,b){wa(a);y(a.status,"Applying changes...");Ka(a.h.url,b,function(c){200==c?ta(a.status):0==c?z(null,"Lost connection"):z(a.status,"Could not apply changes")})}function R(a,b,c){let e=r("button",b);u(a,e);c&&(e.onclick=function(){c(e.closest("tbody"))});return e}function Oa(a,b){a.status=v("span","status");u(b,a.status)}function Pa(a,b){for(a=1;10>=a;++a)for(let c=0;10>c;++c)w("i0"+a.toString(16)+c).checked=b?a-1!=c:!1}
function Qa(a,b,c){c||Oa(b,a);let e=b.h;e.Z&&(R(a,"Clear All",function(){A(b);e.Z(b,!1)}),R(a,"Set Default",function(){A(b);e.Z(b,!0)}));R(a,"Discard Changes",function(){let d=b.h;Ra();y(b.status,"Retrieving...");d.R=null;Sa(b,d.url)});b.G=R(a,"Apply All");b.K||(b.G.disabled=!0);b.G.onclick=function(){let d=e.ma(e.A,e.save(b));d&&(Na(b,e.ha(d)),e.ka&&e.ka(d))};return a}
function Ta(a,b,c){let e=v("div","btns");b&&Oa(a,e);b||c||R(e,"Clear",function(d){aa=Da(a,d);d.parentNode.replaceChild(Ua(a,a.h.A),d);A(a)});b||R(e,"Cut",function(d){aa=Da(a,d);P(a,d,function(f){f.onchange&&A(a,f,!1)});d.parentNode.removeChild(d);A(a)});R(e,b?"Append":"Insert",function(d){var f=d.parentNode.firstChild;let g=0;for(;null!=f;)"interlive"==f.className&&++g,f=f.nextSibling;a.h.T&&a.h.T<=g?ua(a.status,`Max entries (${a.h.T})`):(f=Ua(a,a.h.A),d.parentNode.insertBefore(f,d),aa&&Ca(a,aa,f),
a.K||A(a))});b&&Qa(e,a,!0);return e}function Va(a,b,c){a.sort((e,d)=>{var f=Number.isInteger(+e[b])?+e[b]:e[b];e=Number.isInteger(+e[b])?+d[b]:d[b];f=f<e?-1:f>e?1:0;return c?f:-f})}
function Wa(a,b){null!=a.h.L&&Va(b,a.h.L,a.h.P);let c=a.table,e=0;var d=0;let f=null;for(var g=0;g<c.childNodes.length&&"THEAD"==c.childNodes[g].nodeName;++g)++e;for(g=c.childNodes.length-1;0<=g&&"footer"==c.childNodes[g].className;--g)f=c.childNodes[g],++d;for(;c.childNodes.length-e-d<b.length;)g=Ua(a,a.h.A,a.h.g),f?c.insertBefore(g,f):u(c,g);for(;c.childNodes.length-e-d>b.length;)c.removeChild(c.childNodes[c.childNodes.length-d-1]);for(d=0;d<b.length;++d)Ca(a,b[d],c.childNodes[d+e]);"!dhost.b"==
a.h.url&&(128<=b.length?y(null,"NOTE: first 128 of all hosts are displayed"):y(null,""))}function Xa(a){let b=a.table,c=[];for(let e=0;e<b.childNodes.length-1;++e)b.childNodes[e]&&"THEAD"!=b.childNodes[e].nodeName&&"footer"!=b.childNodes[e].className&&c.push(Da(a,b.childNodes[e]));return c}function Ya(a,b){let c=[];for(let e=0;e<b.length;++e)c[e]=La(a,b[e]);return c}function Za(a,b){let c=[];for(let e=0;e<b.length;++e){let d=Ma(a,b[e]);if(!d)return null;c.push(d)}return c}
function Ua(a,b,c){var e;e||=a.h.list?"interlive":"";let d=v("tbody",e);if("group"!=b[0].t){let f=r("tr");u(d,f);let g;Q(b,!1,function(l,h){l.C&&0!=h||(g=r("td"),u(f,g));u(g,l.t(a,l,h))});c||u(f,x(Ta(a,!1,!0)))}else{let f,g;Q(b,!0,function(l,h){if("group"==l.t)u(d,g=v("tr",l.c||""));else if("string"==typeof l.t){let t;"buttons"==l.t?t=Ta(a,!1):t=r(l.t,l.Aa);u(g,u(x(null,l.span||1),t))}else 0==h&&(l.label?f=x(null,l.span,"lbl"):(l.Da?u(f,q(l.n)):u(g,x(q(l.n?l.n+":":""),1,"lbl")),f=x(null,l.span)),
u(g,f)),u(f,l.t(a,l,h)),l.B&&u(f,q(l.B))})}c||Ha(a,d,b);return d}function ab(a,b,c){b=v("th","cat",b);b.colSpan=c;u(a,u(r("tr"),b))}function bb(a){let b=v("tr","heading");u(a,u(r("thead"),b));return b}function S(a,b){b=v("tbody",b);u(a,b);return b}
function cb(a,b){a.table.className="list";a.table.border=0;var c=a.h;Wa(a,b);a.ea=Ta(a,!0);b=v("tr","match");c=c.A;let e=0;for(let d=1;d<c.length&&"group"!=c[d].t;++d)e+=c[d].span||1,"static"!=c[d].t&&(e+=c[d].span||1);b=u(b,u(x(null,e),a.ea));u(S(a.table,"footer"),b);a.h.buttons&&a.h.buttons(a)}
function db(a,b){a.table.className="table";let c=a.h,e=bb(a.table),d=Ta(a,!0),f=0;Q(c.A,!1,function(g,l){if(!g.C||0==l){let h=v("th","sb",1<g.l&&!g.C?ka(l,c.X):g.n);h.n=f;h.onclick=function(){a.h.L==h.n?a.h.P=!a.h.P:(a.h.P=!0,a.h.L=h.n);for(let t=0;t<h.parentNode.childNodes.length;++t){let p=h.parentNode.childNodes[t];p.textContent=p.firstChild.textContent}u(h,q(a.h.P?"\u25bc":"\u25b2"))};u(e,h);++f}g.unique&&(a.unique=g,a.fa=g.n)});c.g||u(e,v("th","hd","\u00a0"));Wa(a,b);c.g||u(S(a.table,"footer"),
u(v("tr","btns"),x(d,f+1,"btns")))}
function eb(a,b){let c=a.h,e=c.l||10;if(1<e&&!c.xa){var d=bb(a.table);u(d,r("th"));for(let h=0;h<e;++h){const t=r("th",ka(h,c.X));u(d,t)}}let f=S(a.table),g,l;Q(c.A,!0,function(h,t){if("group"==h.t)ab(f,h.n,(c.l||10)+1);else{if(0==t){u(f,g=v("tr","interlive"));var p=r("th",ca[h.n]||h.n);u(g,p)}if(p=h.t(a,h,t)){if(h.ba&&t<h.ba||h.ca&&t>=h.ca)p.style.visibility="hidden";h.C&&0!=t||(l=r("td"),u(g,l));u(l,p)}}});c.g||(d=v("div","btns"),u(T(f,e+1),Qa(d,a)),Ha(a,a.table,c.A));Ca(a,b);if(c.ra)for(b=1;10>=
b;++b)w("i0"+b.toString(16)+(b-1)).disabled=!0}
function fb(a,b){let c=a.h;var e=c.l||10;let d=bb(a.table);u(d,r("th"));let f=S(a.table),g=[];for(let h=0;h<e;++h)g[h]=v("tr","interlive"),u(f,g[h]),u(g[h],r("th",ka(c.ports?c.ports[h]:h,c.X)));let l=0;Q(c.A,!0,function(h,t){if("group"!=h.t){if(0==t){var p=void 0;ja(h.t(a,h,0),"number")&&(p="number");u(d,v("th",p,ca[h.n]||h.n));++l}if(p=h.t(a,h,t)){if(h.ba&&t<h.ba||h.ca&&t>=h.ca)p.style.visibility="hidden";h=void 0;ja(p,"number")&&(h="number");u(g[t],u(v("td",h),p))}}});c.g||(e=v("div","btns"),u(T(f,
l+1),Qa(e,a)),Ha(a,a.table,c.A));Ca(a,b)}function gb(a,b,c){if(a){var e=a.h,d=a.table;wa(a);d.textContent="";a.table.className="table props";e.g&&(a.table.className+=" ro");e.S(a,b);b=a.table;d=e.ua;let f=r("thead"),g=b.rows[0],l=0;for(let h=0;h<g.cells.length;++h)l+=g.cells[h].colSpan;ab(f,d||"",l);b.insertBefore(f,b.firstChild);if(e.onload)e.onload();e.refresh&&hb(a);c&&A(a)}}let ib=0;
function jb(a,b,c){a&&a.m&&a.m.abort();let e=new XMLHttpRequest;a&&(a.m=e);e.onreadystatechange=function(){if(4==e.readyState){let d=e.status,f=e.responseText;a&&(a.m=null);if(200==d){ib=0;ra&&ta(null);try{let g=eval("("+f+")");a?c(a,a.h.oa(a.h.A,g)):c(a,g)}catch(g){z(null,g)}}else 0==d?(c(a,null),2==++ib&&(z(null,"Lost Connection"),ra=!0)):(401==d?(w("logout").style.display="none",y(null,"Refresh page to log in")):z(null,"Could not retrieve data"),kb())}};e.open("GET",b,!0);e.send(null)}
let lb=[],mb=!1;function nb(a){mb||jb(a,a.h.url,function(b,c){c&&b.h.load(b,c,null,!0)})}function hb(a){let b=setInterval(function(){nb(a)},a.h.refresh);lb.push(b)}function Ra(){for(let a=0;a<lb.length;++a)clearInterval(lb[a]);lb=[]}function kb(){w("main").textContent="";Ra()}function ob(a){this.h=a;this.table=r("table");this.table.cellSpacing=0;this.table.width="100%";this.unique=this.Y=this.K=!1;this.fa=null;this.J=[];this.$=!1;this.m=this.status=this.G=this.ea=null;this.F={}}
function Sa(a,b){jb(a,b,function(c,e){e?gb(c,e):setTimeout(function(){c&&Sa(c,b)},1E3)})}let U=null;function T(a,b){let c=v("div","btns");u(a,u(v("tr","btns"),x(c,b||6,"btns")));return c}function pb(a,b,c){b=b||"/reboot";y(a,c||"Rebooting...");Ra();Ka(b,"*",function(e){200==e?setTimeout(function(){location.reload()},3E3):z(null,"Lost connection")})}function qb(a,b,c,e,d){R(a,b,function(){d?confirm(d)&&pb(null,c,e):pb(null,c,e)})}
function V(a,b,c){let e=v("tr","interlive");b=r("th",b);u(e,b);u(a,u(e,x(c)))}
function rb(a){if(a.F.U.value!=a.F.qa.value)z(a.status,"New passwords do not match");else if(15<a.F.la.value.length)z(a.status,"Bad old password");else if(15<a.F.U.value.length)z(a.status,"New password is too long");else if(15<a.F.U.value.length)z(a.status,"New password is too long");else if(/^[\x00-\x7F]*$/.test(a.F.U.value)){y(a.status,"Changing password...");var b={};b.i01=qa(a.F.U.value,a.F.la.value);mb=!0;Ka("/!pwd.b",Ia(b),function(c){mb=!1;200==c?location.reload():0==c?z(null,"Lost connection"):
405==c?z(a.status,"Incorrect old password"):z(a.status,"Could not change password")})}else z(a.status,"Bad symbol in password")}function sb(a){var b=S(a.table);V(b,"Old Password",a.F.la=xa("opwd"));V(b,"New Password",a.F.U=xa("npwd"));V(b,"Confirm Password",a.F.qa=xa("cpwd"));b=T(b,2);Oa(a,b);R(b,"Change Password",function(){rb(a)})}
function tb(a){var b=S(a.table);V(b,"Backup to Restore",ia());b=T(b,2);Oa(a,b);R(b,"Restore Backup",function(){let c=w("file");if(""==c.value)z(a.status,"no backup file was selected");else{Ra();va(a.status,"Restoring backup... (Please do not interrupt)");var e=new FormData;e.append("file",c.files[0]);var d=new XMLHttpRequest;d.onreadystatechange=function(){d.readyState==XMLHttpRequest.DONE&&pb(a.status)};d.open("POST","/backup.swb");d.send(e)}});R(b,"Save Backup",function(){ub("backup.swb",null,function(c){if(c){c=
"css610g_"+ba.split(".").slice(0,-1).join(".")+".swb";let e=r("a");e.href="backup.swb";e.setAttribute("download",c);e.click()}else y(a.status,"Default configuration. Nothing to save.")})});qb(b,"Reset Configuration","/reset","Resetting configuration...","Are you sure you want to reset configuration?")}function vb(a){a=S(a.table);a=T(a,2);a.style.padding="24 0 8 0";qb(a,"Reboot")}
function ub(a,b,c){let e=new XMLHttpRequest;e.onreadystatechange=function(){4==e.readyState&&(200==e.status?c(e.response):c(null))};e.open("GET",a);null!=b&&(e.responseType=b);e.send()}function wb(a){a=a.replace("alpha",".");a=a.replace("rc",".");a=a.replace("p","");a=a.trim();a=a.split(".").map(Number);3==a.length&&a.splice(2,0,0);return a}function xb(a){let b=wb(ba);a=wb(a);return b[0]>a[0]?!1:99==b[1]?!0:b[1]>a[1]||b[2]>a[2]&&0!=a[2]||b[0]==a[0]&&b[1]==a[1]&&b[2]==a[2]&&b[3]>=a[3]?!1:!0}
function yb(a){a=a.split(".");let b=1E3*Number(a.pop());return 0==b?a.join("."):a.join(".")+` <i>(built at ${(new Date(b)).toString()})</i>`}function zb(a,b){Ka("/pboot","*",function(c){if(200==c){c=new FormData;c.append("blob",b);let e=new XMLHttpRequest;e.onreadystatechange=function(){4==e.readyState&&(200==e.status?(va(a.status,"Upgraded"),pb(a.status)):z(a.status,"Upgrade failed"))};e.open("POST","/upgrade");e.send(c)}else z(a.status,"upgrade failed")})}
function Ab(a){var b=S(a.table),c=r("span");let e=r("span");V(b,"Current Installed Version",c);V(b,"Latest Available Version",e);c.innerHTML=yb(ba);let d;b=S(a.table);ab(b,"Changelog",2);c=r("pre");c.id="log";u(b,u(v("tr","interlive"),x(c,2)));b=T(b,2);Oa(a,b);let f=R(b,"Download & Upgrade",function(){y(a.status,"Retrieving...");ub("http://upgrade.mikrotik.com/swoslite/css610g/swos-css610g-"+(d+".bin"),"blob",function(g){null==g?z(a.status,"Could not retrieve firmware"):(w("status").className="important",
va(a.status,"Upgrading... (Please do not interrupt)"),zb(a,g))})});f.disabled=!0;ub("http://upgrade.mikrotik.com/swoslite/css610g/LATEST",null,function(g){null==g?z(a.status,"Could not determine latest version,probably no internet connection.Use manual upgrade."):(e.innerHTML=yb(g),xb(g)?(console.log(g),console.log(g.split("\u00b7")),console.log(g.split(".").slice(0,-1)),console.log(d),d=g.split(".").slice(0,-1).join("."),f.disabled=!1,y(a.status,"New version is available for upgrade")):y(a.status,
"SwOS Lite is up to date"),ub("http://upgrade.mikrotik.com/swoslite/css610g/CHANGELOG",null,function(l){w("log").textContent=l||"Could not retrieve changelog"}))})}function Bb(a){var b=S(a.table);V(b,"File for Upgrade",ia());b=T(b,2);Oa(a,b);R(b,"Upgrade",function(){let c=w("file");""==c.value?z(a.status,"no firmware was selected"):(w("status").className="important",va(a.status,"Upgrading... (Please do not interrupt)"),zb(a,c.files[0]))})}
function Cb(a){if(a=a.i0a){for(let b=0;b<a.length;++b){let c=Aa(a[b]);n[b]=c;ca["From Port"+(b+1)]="From "+c}fa=n.slice();fa[10]="none"}}function Db(a,b,c){for(let e=0;e<a.length;++e){let d=a[e];d.t||(d.t=C);null!=d.l?0==d.l&&(d.l=10):d.l=b;c&&(d.g=1);d.j&&Db(d.j,b,d.g);d.a&&Db(d.a,b,d.g)}}function W(a,b){let c=a.toLowerCase().replace(" ",""),e={};e.id=c;e.title=a.replace(" ","\u00a0");e.aa=[];for(let d=1;d<arguments.length;++d){let f=arguments[d];null!=f&&e.aa.push(f)}k[c]=e}
function Y(a,b,c,e){if("function"==typeof c){var d=c;c={};c.S=d}(c.url=a)&&"!"==a[0]&&(c.g=1);b&&(c.ua=b);c.list?(c.ma=Za,c.oa=Ya,c.save=Xa,c.load=Wa,c.ha=Ja):(c.ma=Ma,c.oa=La,c.save=Da,c.load=Ca,c.ha=Ia);if(3>=arguments.length)return c;c.A=[];for(d=3;d<arguments.length;++d)null!=arguments[d]&&(arguments[d]instanceof Array?c.A=c.A.concat(arguments[d]):c.A.push(arguments[d]));Db(c.A,c.l||10,c.g);c.P=!0;return c}function Eb(a,b,c,e){c.list=1;c.l=1;c.S=db;return Y.apply(null,arguments)}
function Fb(a,b,c,e){c.list=1;c.l=1;c.S=cb;return Y.apply(null,arguments)}function Gb(a,b,c,e){c.l||(c.l=1);c.xa=1;c.S=eb;return Y.apply(null,arguments)}function Z(a,b,c,e){c.ports&&(c.l=c.ports.length);c.sa=1;c.S=fb;return Y.apply(null,arguments)}
function Hb(a){a=a.substring(1);a=k[a]||k.link;for(var b=0;b<m.length;++b){var c=m[b],e=c.h;c.m&&c.m.abort();e.R=null;c.K&&(e.R=e.save(c))}m=[];aa=null;kb();U&&(b=r("a",U.textContent),b.id=U.id,b.href=`#${b.id}`,U.replaceWith(b));b=w(a.id);U=r("h1",b.textContent);U.id=b.id;b.replaceWith(U);for(let d in a.aa)b=a.aa[d],c=new ob(b),m.push(c),(e=w("main"))&&u(e,c.table),b.R||!b.url?(e=b.R,b.R=null,gb(c,e,!!e)):(y(null,"Retrieving..."),Sa(c,b.url))}window.frameLoaded=Hb;
function Ib(a,b){b=r("a",b);b.href=`#${a}`;b.id=a;return b}function Jb(){Kb();var a=w("tabs");if(a){for(let b in k)u(a,Ib(k[b].id,k[b].title));-1<ba.indexOf("p")&&(a=w("nbar"))&&la(a);window.onhashchange=()=>Hb(location.hash);Hb(location.hash)}}window.onload=function Lb(){jb(null,"/sys.b",function(b,c){c?(ba=Aa(c.i06)+"."+c.i0b,jb(null,"/link.b",function(e,d){d?(d&&Cb(d),Jb()):Lb()})):Lb()})};w("logout").onclick=function(){for(let a of m)a.m?.abort();m=[];kb();Ka("/logout","*",function(){location.reload()})};
function Mb(){for(let b=0;10>b;++b){var a=w("i02"+b).checked;w("i08"+b).style.display=w("i07"+b).style.display=a?"inline":"none";w("i05"+b).style.display=w("i03"+b).style.display=a?"none":"inline";a=3;8<=b&&10>b&&(a=6,w("i05"+b).children[4].style.display="none");w("i05"+b).length=a}}function Nb(){for(let a=0;10>a;++a){let b=w("i01"+a).selectedIndex;w("i03"+a).style.display=2==b?"inline":"none"}}
function Ob(){let a=w("i2a0").checked;w("i0e0").disabled=a;w("i0f0").disabled=a;for(let b=0;10>b;++b)w("i01"+b).disabled=a}function Pb(a){a=T(S(a.table),20);R(a,"Reset Counters",function(){Ka("/resetstats","*",function(){})})}function Qb(){var a=2==w("i0a0").selectedIndex;w("i090").disabled=a;a=w("i170").checked;let b=w("i290");if(b.disabled=!a)b.checked=0}
function Kb(){for(var a=1;16>a;++a)ea[a+128]="Trunk"+a;a="10M 100M 1G 10G 200M 2.5G 5G".split(" ");W("Link",Z("link.b","",{refresh:3E3,onload:Mb,X:1,ka:Cb},{n:"Enabled",id:"i01",t:D},{n:"Name",id:"i0a",t:J},{n:"Link Status",id:"i06",N:"i15",M:1,o:["no link","<b>link on</b>","no link",'<b style="color:red">link paused</b>']},{n:"Auto Negotiation",id:"i02",t:D,onclick:Mb},{n:"Speed",t:N,j:[{id:"i08",o:a},{id:"i05",t:E,u:a}]},{n:"Full Duplex",t:N,j:[{id:"i07",M:1,o:["no","yes"]},{id:"i03",t:D}]},{n:"Flow Control Tx/Rx",
t:N,D:" ",j:[{id:"i16",t:D},{id:"i12",t:D},{id:"i13",N:"i14",M:1,o:["off","tx only","rx only","on"]}]},{n:"Hops",id:"i0d",t:F,g:1},{n:"Last Hop",id:"i0e",o:["","link ok",'<b style="color:red">no link</b>']},{n:"Length",id:"i0f",t:F,g:1,B:"m"},{n:"Fault At",id:"i10",t:F,g:1,B:"m"},{n:"Cable Pairs",id:"i11",t:ya,u:["_","S","O","P"],ga:4,I:4,va:["","Short","Open","Reversed Polarity"]}));W("SFP",Z("sfp.b","SFP",{refresh:1E3,X:2,l:2,g:1},{n:"Vendor",id:"i01",t:J},{n:"Part Number",id:"i02",t:J},{n:"Revision",
id:"i03",t:J},{n:"Serial",id:"i04",t:J},{n:"Date",id:"i05",t:J},{n:"Type",id:"i06",t:J,W:32,za:1},{n:"Temperature",id:"i08",t:za,g:1,B:"C",i:-128},{n:"Voltage",id:"i09",t:F,B:"V",scale:1E3},{n:"Tx Bias",id:"i0a",t:F,B:"mA",scale:1},{n:"Tx Power",id:"i0b",t:F,B:"dBm",scale:1E4,ia:1},{n:"Rx Power",id:"i0c",t:F,B:"dBm",scale:1E4,ia:1}));a=[];for(let b=1;10>=b;++b)a.push({n:"From Port"+b,id:"i0"+b.toString(16),t:D,C:1});W("Port Isolation",Gb("fwd.b","",{l:10,Z:Pa,ra:1},a));W("LAG",Z("lacp.b","",{refresh:3E3,
onload:Nb},{n:"Mode",id:"i01",t:E,onchange:Nb,u:["passive","active","static"]},{n:"Group",id:"i03",t:F,max:15},{n:"Trunk",id:"i02",t:F,g:1},{n:"Partner",id:"i04",t:G,g:1}));W("Forwarding",Z("fwd.b","",{},{n:"Port Lock",t:"group"},{n:"Port Lock",id:"i10",t:D},{n:"Lock On First",id:"i11",t:D},{n:"Port Mirroring",t:"group"},{n:"Mirror Ingress",id:"i12",t:D},{n:"Mirror Egress",id:"i13",t:D},{n:"Mirror To",id:"i14",t:D,na:1},{n:"Storm Rate",id:"i1a",t:F,j:1,scale:1E-5,I:6,max:65535},{n:"Limit Unknown Unicast",
id:"i1b",t:D},{n:"Flood Unknown Multicast",id:"i1c",t:D},{n:"Ingress Rate",id:"i1d",t:F,j:1,scale:1E-5,I:6,max:65535},{n:"Egress Rate",id:"i1e",t:F,j:1,scale:1E-5,I:6,max:65535}));W("RSTP",Gb("sys.b","General",{refresh:1E3,onload:Ob},{n:"Bridge Priority (hex)",t:F,id:"i0e",m:1,O:16,width:4},{n:"Forward Reserved Multicast",t:D,id:"i2a",onclick:Ob},{n:"Port Cost Mode",t:E,id:"i0f",u:["short","long"]},{n:"Root Bridge",t:O,D:".",g:1,a:[{id:"i10",t:F,O:16,m:1,width:4},{id:"i11",t:G,V:1}]}),Z("rstp.b",
"Per Port",{refresh:1E3,onload:Ob},{n:"RSTP",id:"i01",t:D},{n:"Mode",id:"i05",g:1,M:1,o:["STP","RSTP"]},{n:"Role",id:"i02",o:["disabled","alternate","root","designated","backup"]},{n:"Root Path Cost",id:"i03",t:F,g:1},{n:"Type",id:"i06",N:"i07",M:1,o:["shared","point-to-point","edge","edge"]},{n:"State",id:"i08",N:"i09",M:1,o:["discarding","learning","forwarding","forwarding"]}));W("Stats",Z("!stats.b","",{refresh:1E3,g:1},{n:"Rx Rate",id:"i21",scale:.32,j:1,w:7},{n:"Tx Rate",id:"i22",scale:.32,j:1,
w:7},{n:"Rx Packet Rate",id:"i25",scale:2.56,j:1,w:6},{n:"Tx Packet Rate",id:"i26",scale:2.56,j:1,w:6},{n:"Rx Bytes",id:"i01",H:"i02"},{n:"Tx Bytes",id:"i0f",H:"i10"},{n:"Rx Total Packets",id:"i23"},{n:"Tx Total Packets",id:"i24"},{n:"Rx Unicasts",id:"i05",H:"i27"},{n:"Tx Unicasts",id:"i11",H:"i28"},{n:"Rx Broadcasts",id:"i07",H:"i29"},{n:"Tx Broadcasts",id:"i14",H:"i2a"},{n:"Rx Multicasts",id:"i08",H:"i2b"},{n:"Tx Multicasts",id:"i13",H:"i2c"}),Y(null,"",Pb));W("Errors",Z("!stats.b","",{refresh:1E3,
g:1},{n:"Rx Pauses",id:"i17"},{n:"Rx Errors",id:"i1d"},{n:"Rx FCS Errors",id:"i1e"},{n:"Rx Jabber",id:"i1c"},{n:"Rx Runts",id:"i19"},{n:"Rx Fragments",id:"i1a"},{n:"Rx Too Long",id:"i1b"},{n:"Tx Pauses",id:"i16"},{n:"Tx FCS Errors",id:"i04"},{n:"Tx Collisions",id:"i1f"},{n:"Tx Single Collisions",id:"i15"},{n:"Tx Multiple Collisions",id:"i18"},{n:"Tx Excessive Collisions",id:"i12"},{n:"Tx Late Collisions",id:"i20"},{n:"Tx Deferred",id:"i06"}),Y(null,"",Pb));W("Hist",Z("!stats.b","",{refresh:1E3,g:1},
{n:"64",id:"i09"},{n:"65-127",id:"i0a"},{n:"128-255",id:"i0b"},{n:"256-511",id:"i0c"},{n:"512-1023",id:"i0d"},{n:"1024-max",id:"i0e"}),Y(null,"",Pb));W("VLAN",Z("fwd.b","",{},{n:"Ingress",t:"group"},{n:"VLAN Mode",id:"i15",t:E,u:["disabled","optional","strict"]},{n:"VLAN Receive",id:"i17",t:E,u:["any","only tagged","only untagged"]},{n:"Default VLAN ID",id:"i18",t:F,m:1,min:1,max:4095},{n:"Force VLAN ID",id:"i19",t:D},{n:"Egress",t:"group"}));W("VLANs",Eb("vlan.b","",{L:0,T:250},{n:"VLAN ID",t:F,
id:"i01",m:1,min:1,max:4094,unique:1},{n:"IGMP Snooping",id:"i03",t:D},{n:"Members",id:"i02",t:D,C:1,l:10,i:268435455}));W("Hosts",Eb("host.b","Static Hosts",{L:1,T:12},{n:"Port",t:E,id:"i02",u:n},{n:"MAC",t:G,id:"i01",V:0}),Eb("!dhost.b","",{refresh:2E3,g:1,L:1},{n:"Port",id:"i02",o:n,ja:ea},{n:"MAC",t:G,id:"i01",i:"x"}));W("IGMP",Eb("!igmp.b","",{refresh:5E3,g:1,L:0},{n:"Group Address",t:I,id:"i01"},{n:"VLAN",t:F,id:"i03"},{n:"Member Ports",id:"i02",t:D,C:1,l:10}));W("SNMP",Gb("snmp.b","",{},{n:"Enabled",
t:D,id:"i01"},{n:"Community",t:J,id:"i02",W:63},{n:"Contact Info",t:J,id:"i03",W:63},{n:"Location",t:J,id:"i04",W:63}));W("ACL",Fb("acl.b","",{T:32},{t:"group",c:"match"},{n:"From",t:D,id:"i01",l:10,i:1,C:1},{n:"Account as",t:E,id:"i18",span:5,u:["none","#1","#2","#3","#4"]},{t:"buttons",span:5},{t:"group",c:"match"},{n:"MAC Src",t:O,D:"/",a:[{t:G,id:"i02"},{t:G,id:"i03",i:"f"}]},{n:"MAC Dst",t:O,D:"/",span:5,a:[{t:G,id:"i04"},{t:G,id:"i05",i:"f"}]},{n:"Ethertype",t:F,id:"i06",O:16},{t:"span",span:2,
Aa:"hex"},{t:"group",c:"match"},{n:"VLAN",t:E,id:"i07",u:["any","present","not present"]},{n:"VLAN ID",t:F,id:"i08",max:4095,span:5},{n:"Priority",t:F,id:"i09",max:7,i:8},{t:"span",span:2},{t:"group",c:"match"},{n:"IP Src",t:O,D:":",a:[{t:O,D:"/",a:[{t:I,id:"i0a"},{t:F,id:"i0b",max:32}]},{t:F,id:"i0c",max:65535}]},{n:"IP Dst",t:O,D:":",span:5,a:[{t:O,D:"/",a:[{t:I,id:"i0d"},{t:F,id:"i0e",max:32}]},{t:F,id:"i0f",max:65535}]},{n:"Protocol",t:F,id:"i10",max:255},{n:"DSCP",t:F,id:"i11",max:63,i:64},{t:"group",
c:"act"},{n:"Redirect To",t:E,id:"i14",u:fa,i:10},{n:"Mirror To",t:E,id:"i13",u:fa,i:10},{B:"Drop",t:D,id:"i12",Ca:0},{n:"Set VLAN ID",t:F,id:"i15",max:4095},{n:"Priority",t:F,id:"i16",max:7,i:8},{n:"DSCP",t:F,id:"i17",max:63,i:64},{t:"group"},{t:"hr",span:12}));W("ACL Stats",Z("!aclstats.b","",{refresh:1E3,g:1},{n:"Counter #1",id:"i01"},{n:"Counter #2",id:"i02"},{n:"Counter #3",id:"i03"},{n:"Counter #4",id:"i04"}),Y(null,"",Pb));W("Health",Gb("sys.b","",{refresh:1E3,g:1},{n:"CPU Temperature",id:"i22",
g:1,t:za,B:"C"}));W("System",Gb("sys.b","General",{refresh:1E3,onload:Qb},{n:"Address Acquisition",t:E,id:"i0a",u:["DHCP with fallback","static","DHCP only"],onchange:Qb},{n:"Static IP Address",t:I,id:"i09"},{n:"Identity",t:J,id:"i05"},{n:"Allow From",t:O,D:"/",a:[{t:I,id:"i19"},{t:F,id:"i1a",max:32}]},{n:"Allow From Ports",t:D,id:"i12",l:10,C:1},{n:"Allow From VLAN",t:F,id:"i1b",max:4095},{n:"IGMP Snooping",t:D,id:"i17",onclick:Qb},{n:"IGMP Querier",t:D,id:"i29"},{n:"IGMP Fast Leave",t:D,id:"i27",
l:10,C:1},{n:"IGMP Version",t:E,id:"i28",u:["v2","v3"]},{n:"Mikrotik Discovery Protocol",t:D,id:"i08",l:10,C:1},{n:"Serial Number",t:J,id:"i04",g:1},{n:"MAC Address",t:G,id:"i03",g:1},{n:"Model",t:J,id:"i07",g:1},{n:"Uptime",t:Ba,scale:1,id:"i01",g:1},{n:"DHCP & PPPoE Snooping",t:"group"},{n:"Trusted Ports",t:D,id:"i13",l:10,C:1},{n:"Add Information Option",t:D,id:"i14"}),Y(null,"Password Change",sb),Y(null,"Backup",tb),Y(null,"",vb));W("Upgrade",Y(null,"Firmware",Ab),Y(null,"Manual Upgrade",Bb))}
;
