"""
Utility functions and built-in rules for nitro-validator.
"""

from .rules import (
    # Basic rules
    RequiredRule,
    OptionalRule,
    # String rules
    AlphaRule,
    AlphanumericRule,
    EmailRule,
    UrlRule,
    RegexRule,
    LowercaseRule,
    UppercaseRule,
    AlphaDashRule,
    StartsWithRule,
    EndsWithRule,
    ContainsRule,
    UuidRule,
    IpRule,
    Ipv4Rule,
    Ipv6Rule,
    JsonRule,
    SlugRule,
    AsciiRule,
    Base64Rule,
    HexColorRule,
    CreditCardRule,
    MacAddressRule,
    TimezoneRule,
    LocaleRule,
    # Numeric rules
    NumericRule,
    IntegerRule,
    MinRule,
    MaxRule,
    BetweenRule,
    PositiveRule,
    NegativeRule,
    DivisibleByRule,
    # Comparison rules
    SameRule,
    DifferentRule,
    InRule,
    NotInRule,
    # Boolean rules
    BooleanRule,
    # Date rules
    DateRule,
    BeforeRule,
    AfterRule,
    DateEqualsRule,
    DateFormatRule,
    # Convenience rules
    ConfirmedRule,
    AcceptedRule,
    DeclinedRule,
    # Length rules
    LengthRule,
    # Collection rules
    ArrayRule,
    SizeRule,
    DistinctRule,
)

__all__ = [
    "RequiredRule",
    "OptionalRule",
    "AlphaRule",
    "AlphanumericRule",
    "EmailRule",
    "UrlRule",
    "RegexRule",
    "LowercaseRule",
    "UppercaseRule",
    "AlphaDashRule",
    "StartsWithRule",
    "EndsWithRule",
    "ContainsRule",
    "UuidRule",
    "IpRule",
    "Ipv4Rule",
    "Ipv6Rule",
    "JsonRule",
    "SlugRule",
    "AsciiRule",
    "Base64Rule",
    "HexColorRule",
    "CreditCardRule",
    "MacAddressRule",
    "TimezoneRule",
    "LocaleRule",
    "NumericRule",
    "IntegerRule",
    "MinRule",
    "MaxRule",
    "BetweenRule",
    "PositiveRule",
    "NegativeRule",
    "DivisibleByRule",
    "SameRule",
    "DifferentRule",
    "InRule",
    "NotInRule",
    "BooleanRule",
    "DateRule",
    "BeforeRule",
    "AfterRule",
    "DateEqualsRule",
    "DateFormatRule",
    "ConfirmedRule",
    "AcceptedRule",
    "DeclinedRule",
    "LengthRule",
    "ArrayRule",
    "SizeRule",
    "DistinctRule",
    "register_builtin_rules",
]


def register_builtin_rules(registry):
    """
    Register all built-in validation rules with a registry.

    Args:
        registry: RuleRegistry instance to register rules with
    """
    rules = [
        RequiredRule,
        OptionalRule,
        AlphaRule,
        AlphanumericRule,
        EmailRule,
        UrlRule,
        RegexRule,
        LowercaseRule,
        UppercaseRule,
        AlphaDashRule,
        StartsWithRule,
        EndsWithRule,
        ContainsRule,
        UuidRule,
        IpRule,
        Ipv4Rule,
        Ipv6Rule,
        JsonRule,
        SlugRule,
        AsciiRule,
        Base64Rule,
        HexColorRule,
        CreditCardRule,
        MacAddressRule,
        TimezoneRule,
        LocaleRule,
        NumericRule,
        IntegerRule,
        MinRule,
        MaxRule,
        BetweenRule,
        PositiveRule,
        NegativeRule,
        DivisibleByRule,
        SameRule,
        DifferentRule,
        InRule,
        NotInRule,
        BooleanRule,
        DateRule,
        BeforeRule,
        AfterRule,
        DateEqualsRule,
        DateFormatRule,
        ConfirmedRule,
        AcceptedRule,
        DeclinedRule,
        LengthRule,
        ArrayRule,
        SizeRule,
        DistinctRule,
    ]

    for rule in rules:
        registry.register(rule)
