"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import utils
from enum import Enum


class OtlpVersionOptions(str, Enum, metaclass=utils.OpenEnumMeta):
    # 0.10.0
    ZERO_DOT_10_DOT_0 = "0.10.0"
    # 1.3.1
    ONE_DOT_3_DOT_1 = "1.3.1"
