"""
Pydantic Models for MONITOR - system/acquired_dns

Runtime validation models for system/acquired_dns configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "AcquiredDnsModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-01-27T21:38:56.169227Z
# ============================================================================