"""
Pydantic Models for CMDB - system/replacemsg_image

Runtime validation models for system/replacemsg_image configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any, Optional
from enum import Enum

# ============================================================================
# Enum Definitions (for fields with 4+ allowed values)
# ============================================================================

class ReplacemsgImageImageTypeEnum(str, Enum):
    """Allowed values for image_type field."""
    GIF = "gif"
    JPG = "jpg"
    TIFF = "tiff"
    PNG = "png"


# ============================================================================
# Main Model
# ============================================================================

class ReplacemsgImageModel(BaseModel):
    """
    Pydantic model for system/replacemsg_image configuration.
    
    Configure replacement message images.
    
    Validation Rules:        - name: max_length=23 pattern=        - image_type: pattern=        - image_base64: max_length=32768 pattern=    """
    
    class Config:
        """Pydantic model configuration."""
        extra = "allow"  # Allow additional fields from API
        str_strip_whitespace = True
        validate_assignment = True  # Validate on attribute assignment
        use_enum_values = True  # Use enum values instead of names
    
    # ========================================================================
    # Model Fields
    # ========================================================================
    
    name: str | None = Field(max_length=23, default=None, description="Image name.")    
    image_type: ReplacemsgImageImageTypeEnum | None = Field(default=ReplacemsgImageImageTypeEnum.PNG, description="Image type.")    
    image_base64: str | None = Field(max_length=32768, default=None, description="Image data.")    
    # ========================================================================
    # Custom Validators
    # ========================================================================
    
    # ========================================================================
    # Helper Methods
    # ========================================================================
    
    def to_fortios_dict(self) -> dict[str, Any]:
        """
        Convert model to FortiOS API payload format.
        
        Returns:
            Dict suitable for POST/PUT operations
        """
        # Export with exclude_none to avoid sending null values
        return self.model_dump(exclude_none=True, by_alias=True)
    
    @classmethod
    def from_fortios_response(cls, data: dict[str, Any]) -> "ReplacemsgImageModel":
        """
        Create model instance from FortiOS API response.
        
        Args:
            data: Response data from API
            
        Returns:
            Validated model instance
        """
        return cls(**data)

# ============================================================================
# Type Aliases for Convenience
# ============================================================================

Dict = dict[str, Any]  # For backward compatibility

# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "ReplacemsgImageModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.4
# Generated: 2026-01-27T21:38:54.903014Z
# ============================================================================