from enum import Enum


class EntityType(str, Enum):
    AUDIT = "audit"
    COUNTERPARTY = "counterparty"
    PRODUCT = "product"
    DEMAND = "demand"
    CUSTOMERORDER = "customerorder"
    INVOICEIN = "invoicein"
    INVOICEOUT = "invoiceout"
    RETAILDEMAND = "retaildemand"
    SALESCHANNEL = "saleschannel"
    STORE = "store"
    PROJECT = "project"
    CURRENCY = "currency"
    BONUSTRANSACTION = "bonustransaction"
    VARIANT = "variant"
    PURCHASEORDER = "purchaseorder"
    SUPPLY = "supply"
    PAYMENTIN = "paymentin"
    CASHIN = "cashin"
    BUNDLE = "bundle"
    ENTER = "enter"
    PURCHASERETURN = "purchasereturn"
    SALESRETURN = "salesreturn"
    RETAILSALESRETURN = "retailsalesreturn"
    MOVE = "move"
    PROCESSING = "processing"
    PROCESSINGORDER = "processingorder"
    LOSS = "loss"
    PRODUCTFOLDER = "productfolder"
    CONSIGNMENT = "consignment"
    WEBHOOK = "webhook"
    STOCK = "stock"
    ASSORTMENT = "assortment"
    SERVICE = "service"
