from datetime import date as _date
from typing import Literal

import pandas as pd

class ExchangeCalendar:
    @property
    def early_closes(self) -> pd.DatetimeIndex: ...
    def is_session(self, date: str | _date) -> bool: ...
    def session_open(self, session: str | _date) -> pd.Timestamp: ...
    def session_close(self, session: str | _date) -> pd.Timestamp: ...
    def sessions_in_range(
        self, start: str | _date, end: str | _date
    ) -> pd.DatetimeIndex: ...
    def date_to_session(
        self, date: str | _date, direction: Literal["next", "previous", "none"] = ...
    ) -> pd.Timestamp: ...

def get_calendar(name: str) -> ExchangeCalendar: ...
