"""Type stubs for pyarrow."""

from typing import Any

class DataType:
    pass

class Field:
    pass

class Schema:
    pass

class Table:
    num_rows: int
    def to_pylist(self) -> list[dict[str, Any]]: ...

def schema(fields: list[Field]) -> Schema: ...
def field(name: str, dtype: DataType) -> Field: ...
def string() -> DataType: ...
def int32() -> DataType: ...
def float32() -> DataType: ...
def timestamp(unit: str) -> DataType: ...
def list_(value_type: DataType, list_size: int = ...) -> DataType: ...
