from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol, runtime_checkable

from litestar_tus.models import UploadInfo


@runtime_checkable
class Upload(Protocol):
    async def write_chunk(self, offset: int, src: AsyncIterator[bytes]) -> int: ...
    async def get_info(self) -> UploadInfo: ...
    async def finish(self) -> None: ...
    async def get_reader(self) -> AsyncIterator[bytes]: ...


@runtime_checkable
class StorageBackend(Protocol):
    async def create_upload(self, info: UploadInfo) -> Upload: ...
    async def get_upload(self, upload_id: str) -> Upload: ...
    async def terminate_upload(self, upload_id: str) -> None: ...
