from __future__ import annotations
from typing import Any

__all__ = ['Engine']

class Engine:
    """Regorus engine."""

    def __init__(self) -> None: ...
    def add_data(self, data: Any) -> None: ...
    def add_data_from_json_file(self, path: str) -> None: ...
    def add_data_json(self, data: str) -> None: ...
    def add_policy(self, path: str, rego: str) -> str: ...
    def add_policy_from_file(self, path: str) -> str: ...
    # Only present if compiled with Rust feature "coverage"
    def clear_coverage_data(self) -> None: ...
    def clear_data(self) -> None: ...
    def clone(self) -> Engine: ...
    def eval_query(self, query: str) -> Any: ...
    def eval_query_as_json(self, query: str) -> str: ...
    def eval_rule(self, rule: str) -> Any: ...
    def eval_rule_as_json(self, rule: str) -> str: ...
    # Only present if compiled with Rust feature "ast"
    def get_ast_as_json(self) -> str: ...
    # Only present if compiled with Rust feature "coverage"
    def get_coverage_report_as_json(self) -> str: ...
    # Only present if compiled with Rust feature "coverage"
    def get_coverage_report_pretty(self) -> str: ...
    def get_packages(self) -> Any: ...
    def get_policies(self) -> str: ...
    def set_enable_coverage(self, enable: bool) -> None: ...
    def set_gather_prints(self, b: bool) -> None: ...
    def set_input(self, input: Any) -> None: ...
    def set_input_from_json_file(self, path: str) -> None: ...
    def set_input_json(self, input: str) -> None: ...
    def set_rego_v0(self, enable: bool) -> None: ...
    def take_prints(self) -> Any: ...
