"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .s3collectorconf import S3CollectorConf, S3CollectorConfTypedDict
from cribl_control_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CollectorS3Type(str, Enum):
    r"""Collector type"""

    S3 = "s3"


class CollectorS3TypedDict(TypedDict):
    r"""S3 collector configuration"""

    type: CollectorS3Type
    r"""Collector type"""
    conf: S3CollectorConfTypedDict
    destructive: NotRequired[bool]
    r"""Delete any files collected (where applicable)"""
    encoding: NotRequired[str]
    r"""Character encoding to use when parsing ingested data."""


class CollectorS3(BaseModel):
    r"""S3 collector configuration"""

    type: CollectorS3Type
    r"""Collector type"""

    conf: S3CollectorConf

    destructive: Optional[bool] = None
    r"""Delete any files collected (where applicable)"""

    encoding: Optional[str] = None
    r"""Character encoding to use when parsing ingested data."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["destructive", "encoding"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
