from typing import List, Optional, Tuple

class Style:
    bold: bool
    italic: bool
    underlined: bool
    strikethrough: bool
    obfuscated: bool

class Color:
    r: int
    g: int
    b: int
    rgb: Tuple[int, int, int]
    name: Optional[str]
    code: Optional[str]
    is_named: bool

    def to_hex(self) -> str: ...

class Span:
    text: str
    color: Optional[Color]
    style: Style

class SpanBuilder:
    def color(self, color: str) -> SpanBuilder: ...
    def bold(self) -> SpanBuilder: ...
    def italic(self) -> SpanBuilder: ...
    def underlined(self) -> SpanBuilder: ...
    def strikethrough(self) -> SpanBuilder: ...
    def obfuscated(self) -> SpanBuilder: ...
    def then(self, text: str) -> SpanBuilder: ...
    def build(self) -> MCText: ...

class MCText:
    def __init__(self) -> None: ...
    @staticmethod
    def parse(text: str) -> MCText: ...
    @staticmethod
    def parse_json(json: str) -> MCText: ...
    def plain_text(self) -> str: ...
    def to_legacy(self) -> str: ...
    def to_json(self) -> str: ...
    def spans(self) -> List[Span]: ...
    def add(self, text: str) -> SpanBuilder: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...

def parse(text: str) -> MCText: ...
def parse_json(json: str) -> MCText: ...
def strip_codes(text: str) -> str: ...
def count_visible_chars(text: str) -> int: ...
def named_colors() -> List[Tuple[str, str, Tuple[int, int, int]]]: ...

class FontSystem:
    @staticmethod
    def modern() -> FontSystem: ...
    @staticmethod
    def legacy() -> FontSystem: ...
    def measure(self, text: str, size: float) -> float: ...

class LayoutOptions:
    def __init__(
        self,
        size: float,
        max_width: Optional[float] = None,
        shadow: bool = False,
    ) -> None: ...

class RenderResult:
    width: int
    height: int
    def data(self) -> bytes: ...
    def to_bytes(self) -> bytes: ...

def render(
    font_system: FontSystem,
    text: MCText,
    width: int,
    height: int,
    options: LayoutOptions,
) -> RenderResult: ...
