from enum import Enum


class ELicensePlatformType(str, Enum):
    AMAZON2NAS = "Amazon2Nas"
    AMAZON2TAPE = "Amazon2Tape"
    APPLICATION = "Application"
    AWSDYNAMODB = "AwsDynamoDb"
    AWSEC2 = "AwsEc2"
    AWSEFS = "AwsEfs"
    AWSFSX = "AwsFsx"
    AWSRDS = "AwsRds"
    AWSRDSCLUSTER = "AwsRdsCluster"
    AWSREDSHIFT = "AwsRedshift"
    AWSREDSHIFTSERVERLESS = "AwsRedshiftServerless"
    AZURE2NAS = "Azure2Nas"
    AZURE2TAPE = "Azure2Tape"
    AZURECOSMOSDB = "AzureCosmosDb"
    AZUREENTRAID = "AzureEntraId"
    AZUREFILESHARE = "AzureFileShare"
    AZURESQL = "AzureSql"
    AZUREVM = "AzureVm"
    CLOUDBACKUP = "CloudBackup"
    CLOUDBACKUPSERVER = "CloudBackupServer"
    CLOUDBACKUPWORKSTATION = "CloudBackupWorkstation"
    CLOUDREPLICA = "CloudReplica"
    FILE2TAPESERVER = "File2TapeServer"
    FILE2TAPESHARE = "File2TapeShare"
    GCPSPANNER = "GcpSpanner"
    GCPSQL = "GcpSql"
    GCPVM = "GcpVm"
    HYPERV = "HyperV"
    IBMAIX = "IbmAix"
    KVM = "Kvm"
    LINUXPPCSERVER = "LinuxPpcServer"
    LINUXSERVER = "LinuxServer"
    LINUXWORKSTATION = "LinuxWorkstation"
    MACSERVER = "MacServer"
    MACWORKSTATION = "MacWorkstation"
    MONGODB = "MongoDB"
    NUTANIXAHV = "NutanixAhv"
    ORACLESOLARIS = "OracleSolaris"
    PROXMOX = "Proxmox"
    S3COMPATIBLE2NAS = "S3Compatible2Nas"
    S3COMPATIBLE2TAPE = "S3Compatible2Tape"
    UNIVERSALCDPWINDOWS = "UniversalCdpWindows"
    UNIXSERVER = "UnixServer"
    UNKNOWN = "Unknown"
    UNSTRUCTUREDDATA = "UnstructuredData"
    UNSTRUCTUREDDATASERVER = "UnstructuredDataServer"
    VMWARE = "VMware"
    WINDOWSSERVER = "WindowsServer"
    WINDOWSWORKSTATION = "WindowsWorkstation"

    def __str__(self) -> str:
        return str(self.value)
