"""PLC API models - Request and Response models."""

from .requests import (
    BackendFilterRequest,
    PLCConnectBatchRequest,
    PLCConnectRequest,
    PLCDisconnectBatchRequest,
    PLCDisconnectRequest,
    PLCQueryRequest,
    TagBatchReadRequest,
    TagBatchWriteRequest,
    TagInfoRequest,
    TagReadRequest,
    TagWriteRequest,
)
from .responses import (
    ActivePLCsResponse,
    BackendInfo,
    BackendInfoResponse,
    BackendsResponse,
    BaseResponse,
    BatchOperationResponse,
    BatchOperationResult,
    BatchTagReadResponse,
    BatchTagWriteResponse,
    BoolResponse,
    DictResponse,
    FloatResponse,
    IntResponse,
    ListResponse,
    PLCInfo,
    PLCInfoResponse,
    PLCStatus,
    PLCStatusResponse,
    StringResponse,
    SystemDiagnostics,
    SystemDiagnosticsResponse,
    TagInfo,
    TagInfoResponse,
    TagListResponse,
    TagReadResponse,
    TagWriteResponse,
)

__all__ = [
    # Request models
    "BackendFilterRequest",
    "PLCConnectRequest",
    "PLCConnectBatchRequest",
    "PLCDisconnectRequest",
    "PLCDisconnectBatchRequest",
    "PLCQueryRequest",
    "TagReadRequest",
    "TagWriteRequest",
    "TagBatchReadRequest",
    "TagBatchWriteRequest",
    "TagInfoRequest",
    # Response models
    "BaseResponse",
    "BoolResponse",
    "StringResponse",
    "IntResponse",
    "FloatResponse",
    "ListResponse",
    "DictResponse",
    "BackendInfo",
    "BackendsResponse",
    "BackendInfoResponse",
    "PLCInfo",
    "PLCStatus",
    "PLCInfoResponse",
    "PLCStatusResponse",
    "ActivePLCsResponse",
    "TagReadResponse",
    "TagWriteResponse",
    "TagListResponse",
    "TagInfo",
    "TagInfoResponse",
    "BatchOperationResult",
    "BatchOperationResponse",
    "BatchTagReadResponse",
    "BatchTagWriteResponse",
    "SystemDiagnostics",
    "SystemDiagnosticsResponse",
]
