-- 2025-10-30 KWS All cumulative changes to Sherlock to migrate from v2 to v3. You only need to run
--                this if the previous upgrade scripts have not been run.
ALTER TABLE `sherlock_crossmatches` 
ADD COLUMN `z_distance` FLOAT NULL DEFAULT NULL AFTER `W1Err`,
ADD COLUMN `z_distance_modulus` FLOAT NULL DEFAULT NULL AFTER `z_distance`,
ADD COLUMN `pz_distance_scale` FLOAT NULL DEFAULT NULL AFTER `z_distance_modulus`,
ADD COLUMN `pz_distance` FLOAT NULL DEFAULT NULL AFTER `pz_distance_scale`,
ADD COLUMN `pz_distance_modulus` FLOAT NULL DEFAULT NULL AFTER `pz_distance`,
ADD COLUMN `best_distance` FLOAT NULL DEFAULT NULL AFTER `pz_distance_modulus`,
ADD COLUMN `best_distance_flag` VARCHAR(9) NULL DEFAULT NULL AFTER `best_distance`,
ADD COLUMN `best_distance_source` VARCHAR(45) NULL DEFAULT NULL AFTER `best_distance_flag`,
ADD COLUMN `direct_distance_cat` varchar(100) AFTER `best_distance_source`,
ADD COLUMN `pz_distance_cat` varchar(100) AFTER `direct_distance_cat`,
ADD COLUMN `sm_axis_arcsec` double AFTER `pz_distance_cat`,
ADD COLUMN `z_distance_cat` varchar(100) AFTER `sm_axis_arcsec`,
ADD COLUMN `z_distance_scale` float AFTER `z_distance_cat`,
ADD COLUMN `W2` float AFTER `z_distance_scale`,
ADD COLUMN `W2Err` float AFTER `W2`,
ADD COLUMN `W3` float AFTER `W2Err`,
ADD COLUMN `W3Err` float AFTER `W3`,
ADD COLUMN `W4` float AFTER `W3Err`,
ADD COLUMN `W4Err` float AFTER `W4`,
ADD KEY `idx_rank_transient_object_id` (`rank`,`transient_object_id`),
CHANGE COLUMN `separationArcsec` `separationArcsec` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `northSeparationArcsec` `northSeparationArcsec` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `eastSeparationArcsec` `eastSeparationArcsec` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `z` `z` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `scale` `scale` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `distance` `distance` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `distance_modulus` `distance_modulus` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `photoZ` `photoZ` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `photoZErr` `photoZErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `physical_separation_kpc` `physical_separation_kpc` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `rankScore` `rankScore` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `major_axis_arcsec` `major_axis_arcsec` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `direct_distance` `direct_distance` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `direct_distance_scale` `direct_distance_scale` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `direct_distance_modulus` `direct_distance_modulus` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `original_search_radius_arcsec` `original_search_radius_arcsec` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `U` `U` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `UErr` `UErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `B` `B` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `BErr` `BErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `V` `V` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `VErr` `VErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `R` `R` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `RErr` `RErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `I` `I` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `IErr` `IErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `J` `J` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `JErr` `JErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `H` `H` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `HErr` `HErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `K` `K` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `KErr` `KErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_u` `_u` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_uErr` `_uErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_g` `_g` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_gErr` `_gErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_r` `_r` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_rErr` `_rErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_i` `_i` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_iErr` `_iErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_z` `_z` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_zErr` `_zErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_y` `_y` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `_yErr` `_yErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `G` `G` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `GErr` `GErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `unkMag` `unkMag` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `unkMagErr` `unkMagErr` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `transientAbsMag` `transientAbsMag` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `W1` `W1` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `W1Err` `W1Err` FLOAT NULL DEFAULT NULL ;
;
